// Generated by rstantools.  Do not edit by hand.

/*
    newPackage is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    newPackage is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with newPackage.  If not, see <http://www.gnu.org/licenses/>.
*/
#ifndef MODELS_HPP
#define MODELS_HPP
#define STAN__SERVICES__COMMAND_HPP
#ifndef USE_STANC3
#define USE_STANC3
#endif
#include <rstan/rstaninc.hpp>
// Code generated by stanc v2.32.2
#include <stan/model/model_header.hpp>
namespace model_linRegHorseShoe_namespace {
using stan::model::model_base_crtp;
using namespace stan::math;
stan::math::profile_map profiles__;
static constexpr std::array<const char*, 72> locations_array__ =
  {" (found before start of program)",
  " (in 'linRegHorseShoe', line 15, column 2 to column 19)",
  " (in 'linRegHorseShoe', line 16, column 2 to column 19)",
  " (in 'linRegHorseShoe', line 17, column 2 to column 27)",
  " (in 'linRegHorseShoe', line 18, column 2 to column 23)",
  " (in 'linRegHorseShoe', line 19, column 2 to column 30)",
  " (in 'linRegHorseShoe', line 20, column 2 to column 30)",
  " (in 'linRegHorseShoe', line 21, column 2 to column 37)",
  " (in 'linRegHorseShoe', line 22, column 2 to column 37)",
  " (in 'linRegHorseShoe', line 25, column 2 to column 24)",
  " (in 'linRegHorseShoe', line 26, column 2 to column 35)",
  " (in 'linRegHorseShoe', line 27, column 2 to column 20)",
  " (in 'linRegHorseShoe', line 28, column 2 to column 23)",
  " (in 'linRegHorseShoe', line 29, column 2 to column 18)",
  " (in 'linRegHorseShoe', line 58, column 2 to column 20)",
  " (in 'linRegHorseShoe', line 30, column 2 to column 74)",
  " (in 'linRegHorseShoe', line 31, column 2 to column 41)",
  " (in 'linRegHorseShoe', line 32, column 2 to column 98)",
  " (in 'linRegHorseShoe', line 33, column 2 to column 34)",
  " (in 'linRegHorseShoe', line 34, column 2 to column 55)",
  " (in 'linRegHorseShoe', line 62, column 19 to column 100)",
  " (in 'linRegHorseShoe', line 62, column 4 to column 100)",
  " (in 'linRegHorseShoe', line 61, column 9 to line 63, column 3)",
  " (in 'linRegHorseShoe', line 60, column 19 to column 100)",
  " (in 'linRegHorseShoe', line 60, column 4 to column 100)",
  " (in 'linRegHorseShoe', line 59, column 12 to line 61, column 3)",
  " (in 'linRegHorseShoe', line 59, column 2 to line 63, column 3)",
  " (in 'linRegHorseShoe', line 37, column 2 to column 35)",
  " (in 'linRegHorseShoe', line 39, column 2 to column 26)",
  " (in 'linRegHorseShoe', line 40, column 2 to column 31)",
  " (in 'linRegHorseShoe', line 41, column 2 to column 33)",
  " (in 'linRegHorseShoe', line 43, column 2 to column 30)",
  " (in 'linRegHorseShoe', line 44, column 2 to column 34)",
  " (in 'linRegHorseShoe', line 46, column 4 to column 31)",
  " (in 'linRegHorseShoe', line 45, column 12 to line 47, column 3)",
  " (in 'linRegHorseShoe', line 45, column 2 to line 47, column 3)",
  " (in 'linRegHorseShoe', line 49, column 2 to column 29)",
  " (in 'linRegHorseShoe', line 48, column 12 to line 50, column 1)",
  " (in 'linRegHorseShoe', line 48, column 2 to line 50, column 1)",
  " (in 'linRegHorseShoe', line 54, column 2 to column 49)",
  " (in 'linRegHorseShoe', line 53, column 7 to line 55, column 1)",
  " (in 'linRegHorseShoe', line 52, column 2 to column 52)",
  " (in 'linRegHorseShoe', line 51, column 10 to line 53, column 1)",
  " (in 'linRegHorseShoe', line 51, column 0 to line 55, column 1)",
  " (in 'linRegHorseShoe', line 2, column 2 to column 8)",
  " (in 'linRegHorseShoe', line 3, column 2 to column 8)",
  " (in 'linRegHorseShoe', line 4, column 2 to column 9)",
  " (in 'linRegHorseShoe', line 5, column 2 to column 9)",
  " (in 'linRegHorseShoe', line 6, column 2 to column 13)",
  " (in 'linRegHorseShoe', line 7, column 2 to column 23)",
  " (in 'linRegHorseShoe', line 8, column 9 to column 10)",
  " (in 'linRegHorseShoe', line 8, column 2 to column 12)",
  " (in 'linRegHorseShoe', line 9, column 26 to column 27)",
  " (in 'linRegHorseShoe', line 9, column 2 to column 29)",
  " (in 'linRegHorseShoe', line 10, column 9 to column 10)",
  " (in 'linRegHorseShoe', line 10, column 2 to column 25)",
  " (in 'linRegHorseShoe', line 11, column 9 to column 10)",
  " (in 'linRegHorseShoe', line 11, column 12 to column 13)",
  " (in 'linRegHorseShoe', line 11, column 2 to column 17)",
  " (in 'linRegHorseShoe', line 12, column 9 to column 10)",
  " (in 'linRegHorseShoe', line 12, column 12 to column 14)",
  " (in 'linRegHorseShoe', line 12, column 2 to column 19)",
  " (in 'linRegHorseShoe', line 15, column 9 to column 11)",
  " (in 'linRegHorseShoe', line 16, column 9 to column 11)",
  " (in 'linRegHorseShoe', line 18, column 9 to column 13)",
  " (in 'linRegHorseShoe', line 21, column 21 to column 25)",
  " (in 'linRegHorseShoe', line 22, column 21 to column 25)",
  " (in 'linRegHorseShoe', line 26, column 21 to column 25)",
  " (in 'linRegHorseShoe', line 27, column 9 to column 13)",
  " (in 'linRegHorseShoe', line 28, column 9 to column 13)",
  " (in 'linRegHorseShoe', line 29, column 9 to column 10)",
  " (in 'linRegHorseShoe', line 58, column 9 to column 10)"};
#include <stan_meta_header.hpp>
class model_linRegHorseShoe final : public model_base_crtp<model_linRegHorseShoe> {
private:
  int N;
  int K;
  int K2;
  int K1;
  int logitR;
  double varY;
  std::vector<double> y;
  std::vector<int> yL;
  Eigen::Matrix<double,-1,1> yUncertainty_data__;
  Eigen::Matrix<double,-1,-1> X_data__;
  Eigen::Matrix<double,-1,-1> X2_data__;
  int zvalues_1dim__;
  int r1_local_1dim__;
  int r2_local_1dim__;
  int lambda_1dim__;
  int beta_1dim__;
  int betaAll_1dim__;
  Eigen::Map<Eigen::Matrix<double,-1,1>> yUncertainty{nullptr, 0};
  Eigen::Map<Eigen::Matrix<double,-1,-1>> X{nullptr, 0, 0};
  Eigen::Map<Eigen::Matrix<double,-1,-1>> X2{nullptr, 0, 0};
public:
  ~model_linRegHorseShoe() {}
  model_linRegHorseShoe(stan::io::var_context& context__, unsigned int
                        random_seed__ = 0, std::ostream* pstream__ = nullptr)
      : model_base_crtp(0) {
    int current_statement__ = 0;
    using local_scalar_t__ = double;
    boost::ecuyer1988 base_rng__ =
      stan::services::util::create_rng(random_seed__, 0);
    // suppress unused var warning
    (void) base_rng__;
    static constexpr const char* function__ =
      "model_linRegHorseShoe_namespace::model_linRegHorseShoe";
    // suppress unused var warning
    (void) function__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    try {
      int pos__ = std::numeric_limits<int>::min();
      pos__ = 1;
      current_statement__ = 44;
      context__.validate_dims("data initialization", "N", "int",
        std::vector<size_t>{});
      N = std::numeric_limits<int>::min();
      current_statement__ = 44;
      N = context__.vals_i("N")[(1 - 1)];
      current_statement__ = 45;
      context__.validate_dims("data initialization", "K", "int",
        std::vector<size_t>{});
      K = std::numeric_limits<int>::min();
      current_statement__ = 45;
      K = context__.vals_i("K")[(1 - 1)];
      current_statement__ = 46;
      context__.validate_dims("data initialization", "K2", "int",
        std::vector<size_t>{});
      K2 = std::numeric_limits<int>::min();
      current_statement__ = 46;
      K2 = context__.vals_i("K2")[(1 - 1)];
      current_statement__ = 47;
      context__.validate_dims("data initialization", "K1", "int",
        std::vector<size_t>{});
      K1 = std::numeric_limits<int>::min();
      current_statement__ = 47;
      K1 = context__.vals_i("K1")[(1 - 1)];
      current_statement__ = 48;
      context__.validate_dims("data initialization", "logitR", "int",
        std::vector<size_t>{});
      logitR = std::numeric_limits<int>::min();
      current_statement__ = 48;
      logitR = context__.vals_i("logitR")[(1 - 1)];
      current_statement__ = 49;
      context__.validate_dims("data initialization", "varY", "double",
        std::vector<size_t>{});
      varY = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 49;
      varY = context__.vals_r("varY")[(1 - 1)];
      current_statement__ = 49;
      stan::math::check_greater_or_equal(function__, "varY", varY, 0);
      current_statement__ = 50;
      stan::math::validate_non_negative_index("y", "N", N);
      current_statement__ = 51;
      context__.validate_dims("data initialization", "y", "double",
        std::vector<size_t>{static_cast<size_t>(N)});
      y = std::vector<double>(N, std::numeric_limits<double>::quiet_NaN());
      current_statement__ = 51;
      y = context__.vals_r("y");
      current_statement__ = 52;
      stan::math::validate_non_negative_index("yL", "N", N);
      current_statement__ = 53;
      context__.validate_dims("data initialization", "yL", "int",
        std::vector<size_t>{static_cast<size_t>(N)});
      yL = std::vector<int>(N, std::numeric_limits<int>::min());
      current_statement__ = 53;
      yL = context__.vals_i("yL");
      current_statement__ = 53;
      stan::math::check_greater_or_equal(function__, "yL", yL, 0);
      current_statement__ = 53;
      stan::math::check_less_or_equal(function__, "yL", yL, 1);
      current_statement__ = 54;
      stan::math::validate_non_negative_index("yUncertainty", "N", N);
      current_statement__ = 55;
      context__.validate_dims("data initialization", "yUncertainty",
        "double", std::vector<size_t>{static_cast<size_t>(N)});
      yUncertainty_data__ = Eigen::Matrix<double,-1,1>::Constant(N,
                              std::numeric_limits<double>::quiet_NaN());
      new (&yUncertainty)
        Eigen::Map<Eigen::Matrix<double,-1,1>>(yUncertainty_data__.data(), N);
      {
        std::vector<local_scalar_t__> yUncertainty_flat__;
        current_statement__ = 55;
        yUncertainty_flat__ = context__.vals_r("yUncertainty");
        current_statement__ = 55;
        pos__ = 1;
        current_statement__ = 55;
        for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
          current_statement__ = 55;
          stan::model::assign(yUncertainty, yUncertainty_flat__[(pos__ - 1)],
            "assigning variable yUncertainty", stan::model::index_uni(sym1__));
          current_statement__ = 55;
          pos__ = (pos__ + 1);
        }
      }
      current_statement__ = 56;
      stan::math::validate_non_negative_index("X", "N", N);
      current_statement__ = 57;
      stan::math::validate_non_negative_index("X", "K", K);
      current_statement__ = 58;
      context__.validate_dims("data initialization", "X", "double",
        std::vector<size_t>{static_cast<size_t>(N), static_cast<size_t>(K)});
      X_data__ = Eigen::Matrix<double,-1,-1>::Constant(N, K,
                   std::numeric_limits<double>::quiet_NaN());
      new (&X) Eigen::Map<Eigen::Matrix<double,-1,-1>>(X_data__.data(), N, K);
      {
        std::vector<local_scalar_t__> X_flat__;
        current_statement__ = 58;
        X_flat__ = context__.vals_r("X");
        current_statement__ = 58;
        pos__ = 1;
        current_statement__ = 58;
        for (int sym1__ = 1; sym1__ <= K; ++sym1__) {
          current_statement__ = 58;
          for (int sym2__ = 1; sym2__ <= N; ++sym2__) {
            current_statement__ = 58;
            stan::model::assign(X, X_flat__[(pos__ - 1)],
              "assigning variable X", stan::model::index_uni(sym2__),
              stan::model::index_uni(sym1__));
            current_statement__ = 58;
            pos__ = (pos__ + 1);
          }
        }
      }
      current_statement__ = 59;
      stan::math::validate_non_negative_index("X2", "N", N);
      current_statement__ = 60;
      stan::math::validate_non_negative_index("X2", "K2", K2);
      current_statement__ = 61;
      context__.validate_dims("data initialization", "X2", "double",
        std::vector<size_t>{static_cast<size_t>(N), static_cast<size_t>(K2)});
      X2_data__ = Eigen::Matrix<double,-1,-1>::Constant(N, K2,
                    std::numeric_limits<double>::quiet_NaN());
      new (&X2) Eigen::Map<Eigen::Matrix<double,-1,-1>>(X2_data__.data(), N,
        K2);
      {
        std::vector<local_scalar_t__> X2_flat__;
        current_statement__ = 61;
        X2_flat__ = context__.vals_r("X2");
        current_statement__ = 61;
        pos__ = 1;
        current_statement__ = 61;
        for (int sym1__ = 1; sym1__ <= K2; ++sym1__) {
          current_statement__ = 61;
          for (int sym2__ = 1; sym2__ <= N; ++sym2__) {
            current_statement__ = 61;
            stan::model::assign(X2, X2_flat__[(pos__ - 1)],
              "assigning variable X2", stan::model::index_uni(sym2__),
              stan::model::index_uni(sym1__));
            current_statement__ = 61;
            pos__ = (pos__ + 1);
          }
        }
      }
      current_statement__ = 62;
      stan::math::validate_non_negative_index("beta0", "K1", K1);
      current_statement__ = 63;
      stan::math::validate_non_negative_index("beta2", "K2", K2);
      current_statement__ = 64;
      zvalues_1dim__ = std::numeric_limits<int>::min();
      current_statement__ = 64;
      zvalues_1dim__ = (K - K1);
      current_statement__ = 64;
      stan::math::validate_non_negative_index("zvalues", "K - K1",
        zvalues_1dim__);
      current_statement__ = 65;
      r1_local_1dim__ = std::numeric_limits<int>::min();
      current_statement__ = 65;
      r1_local_1dim__ = (K - K1);
      current_statement__ = 65;
      stan::math::validate_non_negative_index("r1_local", "K - K1",
        r1_local_1dim__);
      current_statement__ = 66;
      r2_local_1dim__ = std::numeric_limits<int>::min();
      current_statement__ = 66;
      r2_local_1dim__ = (K - K1);
      current_statement__ = 66;
      stan::math::validate_non_negative_index("r2_local", "K - K1",
        r2_local_1dim__);
      current_statement__ = 67;
      lambda_1dim__ = std::numeric_limits<int>::min();
      current_statement__ = 67;
      lambda_1dim__ = (K - K1);
      current_statement__ = 67;
      stan::math::validate_non_negative_index("lambda", "K - K1",
        lambda_1dim__);
      current_statement__ = 68;
      beta_1dim__ = std::numeric_limits<int>::min();
      current_statement__ = 68;
      beta_1dim__ = (K - K1);
      current_statement__ = 68;
      stan::math::validate_non_negative_index("beta", "K - K1", beta_1dim__);
      current_statement__ = 69;
      betaAll_1dim__ = std::numeric_limits<int>::min();
      current_statement__ = 69;
      betaAll_1dim__ = (K + K2);
      current_statement__ = 69;
      stan::math::validate_non_negative_index("betaAll", "K + K2",
        betaAll_1dim__);
      current_statement__ = 70;
      stan::math::validate_non_negative_index("sigma", "N", N);
      current_statement__ = 71;
      stan::math::validate_non_negative_index("log_lik", "N", N);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
    num_params_r__ = K1 + K2 + 1 + zvalues_1dim__ + 1 + 1 + r1_local_1dim__ +
      r2_local_1dim__;
  }
  inline std::string model_name() const final {
    return "model_linRegHorseShoe";
  }
  inline std::vector<std::string> model_compile_info() const noexcept {
    return std::vector<std::string>{"stanc_version = stanc3 v2.32.2",
             "stancflags = --allow-undefined"};
  }
  template <bool propto__, bool jacobian__, typename VecR, typename VecI,
            stan::require_vector_like_t<VecR>* = nullptr,
            stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr>
  inline stan::scalar_type_t<VecR>
  log_prob_impl(VecR& params_r__, VecI& params_i__, std::ostream*
                pstream__ = nullptr) const {
    using T__ = stan::scalar_type_t<VecR>;
    using local_scalar_t__ = T__;
    T__ lp__(0.0);
    stan::math::accumulator<T__> lp_accum__;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    int current_statement__ = 0;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    static constexpr const char* function__ =
      "model_linRegHorseShoe_namespace::log_prob";
    // suppress unused var warning
    (void) function__;
    try {
      Eigen::Matrix<local_scalar_t__,-1,1> beta0 =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(K1, DUMMY_VAR__);
      current_statement__ = 1;
      beta0 = in__.template read<Eigen::Matrix<local_scalar_t__,-1,1>>(K1);
      Eigen::Matrix<local_scalar_t__,-1,1> beta2 =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(K2, DUMMY_VAR__);
      current_statement__ = 2;
      beta2 = in__.template read<Eigen::Matrix<local_scalar_t__,-1,1>>(K2);
      local_scalar_t__ logsigma = DUMMY_VAR__;
      current_statement__ = 3;
      logsigma = in__.template read_constrain_ub<local_scalar_t__,
                   jacobian__>(0, lp__);
      Eigen::Matrix<local_scalar_t__,-1,1> zvalues =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(zvalues_1dim__,
          DUMMY_VAR__);
      current_statement__ = 4;
      zvalues = in__.template read<
                  Eigen::Matrix<local_scalar_t__,-1,1>>(zvalues_1dim__);
      local_scalar_t__ r1_global = DUMMY_VAR__;
      current_statement__ = 5;
      r1_global = in__.template read_constrain_lb<local_scalar_t__,
                    jacobian__>(0, lp__);
      local_scalar_t__ r2_global = DUMMY_VAR__;
      current_statement__ = 6;
      r2_global = in__.template read_constrain_lb<local_scalar_t__,
                    jacobian__>(0, lp__);
      Eigen::Matrix<local_scalar_t__,-1,1> r1_local =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(r1_local_1dim__,
          DUMMY_VAR__);
      current_statement__ = 7;
      r1_local = in__.template read_constrain_lb<
                   Eigen::Matrix<local_scalar_t__,-1,1>, jacobian__>(0, lp__,
                   r1_local_1dim__);
      Eigen::Matrix<local_scalar_t__,-1,1> r2_local =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(r2_local_1dim__,
          DUMMY_VAR__);
      current_statement__ = 8;
      r2_local = in__.template read_constrain_lb<
                   Eigen::Matrix<local_scalar_t__,-1,1>, jacobian__>(0, lp__,
                   r2_local_1dim__);
      local_scalar_t__ tau = DUMMY_VAR__;
      Eigen::Matrix<local_scalar_t__,-1,1> lambda =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(lambda_1dim__,
          DUMMY_VAR__);
      Eigen::Matrix<local_scalar_t__,-1,1> beta =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(beta_1dim__,
          DUMMY_VAR__);
      Eigen::Matrix<local_scalar_t__,-1,1> betaAll =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(betaAll_1dim__,
          DUMMY_VAR__);
      Eigen::Matrix<local_scalar_t__,-1,1> sigma =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(N, DUMMY_VAR__);
      current_statement__ = 15;
      stan::model::assign(sigma,
        stan::math::sqrt(
          stan::math::add(
            stan::math::square((stan::math::exp(logsigma) *
              stan::math::sqrt(varY))), stan::math::square(yUncertainty))),
        "assigning variable sigma");
      current_statement__ = 16;
      stan::model::assign(lambda,
        stan::math::elt_multiply(r1_local, stan::math::sqrt(r2_local)),
        "assigning variable lambda");
      current_statement__ = 17;
      tau = ((r1_global * stan::math::sqrt(r2_global)) *
        stan::math::sqrt((stan::math::square(stan::math::exp(logsigma)) +
          stan::math::mean(stan::math::square(yUncertainty)))));
      current_statement__ = 18;
      stan::model::assign(beta,
        stan::math::multiply(stan::math::elt_multiply(zvalues, lambda), tau),
        "assigning variable beta");
      current_statement__ = 19;
      stan::model::assign(betaAll,
        stan::math::append_row(stan::math::append_row(beta0, beta), beta2),
        "assigning variable betaAll");
      current_statement__ = 9;
      stan::math::check_greater_or_equal(function__, "tau", tau, 0);
      current_statement__ = 10;
      stan::math::check_greater_or_equal(function__, "lambda", lambda, 0);
      {
        current_statement__ = 27;
        lp_accum__.add(stan::math::student_t_lpdf<propto__>(logsigma, 3, -1,
                         1.5));
        current_statement__ = 28;
        lp_accum__.add(stan::math::normal_lpdf<propto__>(zvalues, 0, 1));
        current_statement__ = 29;
        lp_accum__.add(stan::math::normal_lpdf<propto__>(r1_local, 0.0, 1.0));
        current_statement__ = 30;
        lp_accum__.add(stan::math::inv_gamma_lpdf<propto__>(r2_local, 0.5,
                         0.5));
        current_statement__ = 31;
        lp_accum__.add(stan::math::normal_lpdf<propto__>(r1_global, 0.0, 1));
        current_statement__ = 32;
        lp_accum__.add(stan::math::inv_gamma_lpdf<propto__>(r2_global, 0.5,
                         0.5));
        current_statement__ = 35;
        if (stan::math::logical_gt(K1, 0)) {
          current_statement__ = 33;
          lp_accum__.add(stan::math::student_t_lpdf<propto__>(beta0, 1, 0, 5));
        }
        current_statement__ = 38;
        if (stan::math::logical_gt(K2, 0)) {
          current_statement__ = 36;
          lp_accum__.add(stan::math::student_t_lpdf<propto__>(beta2, 3, 0, 5));
        }
        current_statement__ = 43;
        if (logitR) {
          current_statement__ = 41;
          lp_accum__.add(stan::math::bernoulli_logit_lpmf<propto__>(yL,
                           stan::math::multiply(
                             stan::math::append_col(X, X2), betaAll)));
        } else {
          current_statement__ = 39;
          lp_accum__.add(stan::math::normal_lpdf<propto__>(y,
                           stan::math::multiply(
                             stan::math::append_col(X, X2), betaAll), sigma));
        }
      }
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
    lp_accum__.add(lp__);
    return lp_accum__.sum();
  }
  template <typename RNG, typename VecR, typename VecI, typename VecVar,
            stan::require_vector_like_vt<std::is_floating_point,
            VecR>* = nullptr, stan::require_vector_like_vt<std::is_integral,
            VecI>* = nullptr, stan::require_vector_vt<std::is_floating_point,
            VecVar>* = nullptr>
  inline void
  write_array_impl(RNG& base_rng__, VecR& params_r__, VecI& params_i__,
                   VecVar& vars__, const bool
                   emit_transformed_parameters__ = true, const bool
                   emit_generated_quantities__ = true, std::ostream*
                   pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    stan::io::serializer<local_scalar_t__> out__(vars__);
    static constexpr bool propto__ = true;
    // suppress unused var warning
    (void) propto__;
    double lp__ = 0.0;
    // suppress unused var warning
    (void) lp__;
    int current_statement__ = 0;
    stan::math::accumulator<double> lp_accum__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    constexpr bool jacobian__ = false;
    static constexpr const char* function__ =
      "model_linRegHorseShoe_namespace::write_array";
    // suppress unused var warning
    (void) function__;
    try {
      Eigen::Matrix<double,-1,1> beta0 =
        Eigen::Matrix<double,-1,1>::Constant(K1,
          std::numeric_limits<double>::quiet_NaN());
      current_statement__ = 1;
      beta0 = in__.template read<Eigen::Matrix<local_scalar_t__,-1,1>>(K1);
      Eigen::Matrix<double,-1,1> beta2 =
        Eigen::Matrix<double,-1,1>::Constant(K2,
          std::numeric_limits<double>::quiet_NaN());
      current_statement__ = 2;
      beta2 = in__.template read<Eigen::Matrix<local_scalar_t__,-1,1>>(K2);
      double logsigma = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 3;
      logsigma = in__.template read_constrain_ub<local_scalar_t__,
                   jacobian__>(0, lp__);
      Eigen::Matrix<double,-1,1> zvalues =
        Eigen::Matrix<double,-1,1>::Constant(zvalues_1dim__,
          std::numeric_limits<double>::quiet_NaN());
      current_statement__ = 4;
      zvalues = in__.template read<
                  Eigen::Matrix<local_scalar_t__,-1,1>>(zvalues_1dim__);
      double r1_global = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 5;
      r1_global = in__.template read_constrain_lb<local_scalar_t__,
                    jacobian__>(0, lp__);
      double r2_global = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 6;
      r2_global = in__.template read_constrain_lb<local_scalar_t__,
                    jacobian__>(0, lp__);
      Eigen::Matrix<double,-1,1> r1_local =
        Eigen::Matrix<double,-1,1>::Constant(r1_local_1dim__,
          std::numeric_limits<double>::quiet_NaN());
      current_statement__ = 7;
      r1_local = in__.template read_constrain_lb<
                   Eigen::Matrix<local_scalar_t__,-1,1>, jacobian__>(0, lp__,
                   r1_local_1dim__);
      Eigen::Matrix<double,-1,1> r2_local =
        Eigen::Matrix<double,-1,1>::Constant(r2_local_1dim__,
          std::numeric_limits<double>::quiet_NaN());
      current_statement__ = 8;
      r2_local = in__.template read_constrain_lb<
                   Eigen::Matrix<local_scalar_t__,-1,1>, jacobian__>(0, lp__,
                   r2_local_1dim__);
      double tau = std::numeric_limits<double>::quiet_NaN();
      Eigen::Matrix<double,-1,1> lambda =
        Eigen::Matrix<double,-1,1>::Constant(lambda_1dim__,
          std::numeric_limits<double>::quiet_NaN());
      Eigen::Matrix<double,-1,1> beta =
        Eigen::Matrix<double,-1,1>::Constant(beta_1dim__,
          std::numeric_limits<double>::quiet_NaN());
      Eigen::Matrix<double,-1,1> betaAll =
        Eigen::Matrix<double,-1,1>::Constant(betaAll_1dim__,
          std::numeric_limits<double>::quiet_NaN());
      Eigen::Matrix<double,-1,1> sigma =
        Eigen::Matrix<double,-1,1>::Constant(N,
          std::numeric_limits<double>::quiet_NaN());
      out__.write(beta0);
      out__.write(beta2);
      out__.write(logsigma);
      out__.write(zvalues);
      out__.write(r1_global);
      out__.write(r2_global);
      out__.write(r1_local);
      out__.write(r2_local);
      if (stan::math::logical_negation(
            (stan::math::primitive_value(emit_transformed_parameters__) ||
            stan::math::primitive_value(emit_generated_quantities__)))) {
        return ;
      }
      current_statement__ = 15;
      stan::model::assign(sigma,
        stan::math::sqrt(
          stan::math::add(
            stan::math::square((stan::math::exp(logsigma) *
              stan::math::sqrt(varY))), stan::math::square(yUncertainty))),
        "assigning variable sigma");
      current_statement__ = 16;
      stan::model::assign(lambda,
        stan::math::elt_multiply(r1_local, stan::math::sqrt(r2_local)),
        "assigning variable lambda");
      current_statement__ = 17;
      tau = ((r1_global * stan::math::sqrt(r2_global)) *
        stan::math::sqrt((stan::math::square(stan::math::exp(logsigma)) +
          stan::math::mean(stan::math::square(yUncertainty)))));
      current_statement__ = 18;
      stan::model::assign(beta,
        stan::math::multiply(stan::math::elt_multiply(zvalues, lambda), tau),
        "assigning variable beta");
      current_statement__ = 19;
      stan::model::assign(betaAll,
        stan::math::append_row(stan::math::append_row(beta0, beta), beta2),
        "assigning variable betaAll");
      current_statement__ = 9;
      stan::math::check_greater_or_equal(function__, "tau", tau, 0);
      current_statement__ = 10;
      stan::math::check_greater_or_equal(function__, "lambda", lambda, 0);
      if (emit_transformed_parameters__) {
        out__.write(tau);
        out__.write(lambda);
        out__.write(beta);
        out__.write(betaAll);
        out__.write(sigma);
      }
      if (stan::math::logical_negation(emit_generated_quantities__)) {
        return ;
      }
      Eigen::Matrix<double,-1,1> log_lik =
        Eigen::Matrix<double,-1,1>::Constant(N,
          std::numeric_limits<double>::quiet_NaN());
      current_statement__ = 26;
      if (logitR) {
        current_statement__ = 24;
        for (int n = 1; n <= N; ++n) {
          current_statement__ = 23;
          stan::model::assign(log_lik,
            stan::math::bernoulli_logit_lpmf<false>(
              stan::model::rvalue(yL, "yL", stan::model::index_uni(n)),
              stan::math::multiply(
                stan::math::append_col(
                  stan::model::rvalue(X, "X", stan::model::index_uni(n),
                    stan::model::index_omni()),
                  stan::model::rvalue(X2, "X2", stan::model::index_uni(n),
                    stan::model::index_omni())), betaAll)),
            "assigning variable log_lik", stan::model::index_uni(n));
        }
      } else {
        current_statement__ = 21;
        for (int n = 1; n <= N; ++n) {
          current_statement__ = 20;
          stan::model::assign(log_lik,
            stan::math::normal_lpdf<false>(
              stan::model::rvalue(y, "y", stan::model::index_uni(n)),
              stan::math::multiply(
                stan::math::append_col(
                  stan::model::rvalue(X, "X", stan::model::index_uni(n),
                    stan::model::index_omni()),
                  stan::model::rvalue(X2, "X2", stan::model::index_uni(n),
                    stan::model::index_omni())), betaAll),
              stan::model::rvalue(sigma, "sigma", stan::model::index_uni(n))),
            "assigning variable log_lik", stan::model::index_uni(n));
        }
      }
      out__.write(log_lik);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
  }
  template <typename VecVar, typename VecI,
            stan::require_vector_t<VecVar>* = nullptr,
            stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr>
  inline void
  unconstrain_array_impl(const VecVar& params_r__, const VecI& params_i__,
                         VecVar& vars__, std::ostream* pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    stan::io::serializer<local_scalar_t__> out__(vars__);
    int current_statement__ = 0;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    try {
      int pos__ = std::numeric_limits<int>::min();
      pos__ = 1;
      Eigen::Matrix<local_scalar_t__,-1,1> beta0 =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(K1, DUMMY_VAR__);
      current_statement__ = 1;
      stan::model::assign(beta0,
        in__.read<Eigen::Matrix<local_scalar_t__,-1,1>>(K1),
        "assigning variable beta0");
      out__.write(beta0);
      Eigen::Matrix<local_scalar_t__,-1,1> beta2 =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(K2, DUMMY_VAR__);
      current_statement__ = 2;
      stan::model::assign(beta2,
        in__.read<Eigen::Matrix<local_scalar_t__,-1,1>>(K2),
        "assigning variable beta2");
      out__.write(beta2);
      local_scalar_t__ logsigma = DUMMY_VAR__;
      current_statement__ = 3;
      logsigma = in__.read<local_scalar_t__>();
      out__.write_free_ub(0, logsigma);
      Eigen::Matrix<local_scalar_t__,-1,1> zvalues =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(zvalues_1dim__,
          DUMMY_VAR__);
      current_statement__ = 4;
      stan::model::assign(zvalues,
        in__.read<Eigen::Matrix<local_scalar_t__,-1,1>>(zvalues_1dim__),
        "assigning variable zvalues");
      out__.write(zvalues);
      local_scalar_t__ r1_global = DUMMY_VAR__;
      current_statement__ = 5;
      r1_global = in__.read<local_scalar_t__>();
      out__.write_free_lb(0, r1_global);
      local_scalar_t__ r2_global = DUMMY_VAR__;
      current_statement__ = 6;
      r2_global = in__.read<local_scalar_t__>();
      out__.write_free_lb(0, r2_global);
      Eigen::Matrix<local_scalar_t__,-1,1> r1_local =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(r1_local_1dim__,
          DUMMY_VAR__);
      current_statement__ = 7;
      stan::model::assign(r1_local,
        in__.read<Eigen::Matrix<local_scalar_t__,-1,1>>(r1_local_1dim__),
        "assigning variable r1_local");
      out__.write_free_lb(0, r1_local);
      Eigen::Matrix<local_scalar_t__,-1,1> r2_local =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(r2_local_1dim__,
          DUMMY_VAR__);
      current_statement__ = 8;
      stan::model::assign(r2_local,
        in__.read<Eigen::Matrix<local_scalar_t__,-1,1>>(r2_local_1dim__),
        "assigning variable r2_local");
      out__.write_free_lb(0, r2_local);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
  }
  template <typename VecVar, stan::require_vector_t<VecVar>* = nullptr>
  inline void
  transform_inits_impl(const stan::io::var_context& context__, VecVar&
                       vars__, std::ostream* pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    stan::io::serializer<local_scalar_t__> out__(vars__);
    int current_statement__ = 0;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    try {
      current_statement__ = 1;
      context__.validate_dims("parameter initialization", "beta0", "double",
        std::vector<size_t>{static_cast<size_t>(K1)});
      current_statement__ = 2;
      context__.validate_dims("parameter initialization", "beta2", "double",
        std::vector<size_t>{static_cast<size_t>(K2)});
      current_statement__ = 3;
      context__.validate_dims("parameter initialization", "logsigma",
        "double", std::vector<size_t>{});
      current_statement__ = 4;
      context__.validate_dims("parameter initialization", "zvalues",
        "double", std::vector<size_t>{static_cast<size_t>(zvalues_1dim__)});
      current_statement__ = 5;
      context__.validate_dims("parameter initialization", "r1_global",
        "double", std::vector<size_t>{});
      current_statement__ = 6;
      context__.validate_dims("parameter initialization", "r2_global",
        "double", std::vector<size_t>{});
      current_statement__ = 7;
      context__.validate_dims("parameter initialization", "r1_local",
        "double", std::vector<size_t>{static_cast<size_t>(r1_local_1dim__)});
      current_statement__ = 8;
      context__.validate_dims("parameter initialization", "r2_local",
        "double", std::vector<size_t>{static_cast<size_t>(r2_local_1dim__)});
      int pos__ = std::numeric_limits<int>::min();
      pos__ = 1;
      Eigen::Matrix<local_scalar_t__,-1,1> beta0 =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(K1, DUMMY_VAR__);
      {
        std::vector<local_scalar_t__> beta0_flat__;
        current_statement__ = 1;
        beta0_flat__ = context__.vals_r("beta0");
        current_statement__ = 1;
        pos__ = 1;
        current_statement__ = 1;
        for (int sym1__ = 1; sym1__ <= K1; ++sym1__) {
          current_statement__ = 1;
          stan::model::assign(beta0, beta0_flat__[(pos__ - 1)],
            "assigning variable beta0", stan::model::index_uni(sym1__));
          current_statement__ = 1;
          pos__ = (pos__ + 1);
        }
      }
      out__.write(beta0);
      Eigen::Matrix<local_scalar_t__,-1,1> beta2 =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(K2, DUMMY_VAR__);
      {
        std::vector<local_scalar_t__> beta2_flat__;
        current_statement__ = 2;
        beta2_flat__ = context__.vals_r("beta2");
        current_statement__ = 2;
        pos__ = 1;
        current_statement__ = 2;
        for (int sym1__ = 1; sym1__ <= K2; ++sym1__) {
          current_statement__ = 2;
          stan::model::assign(beta2, beta2_flat__[(pos__ - 1)],
            "assigning variable beta2", stan::model::index_uni(sym1__));
          current_statement__ = 2;
          pos__ = (pos__ + 1);
        }
      }
      out__.write(beta2);
      local_scalar_t__ logsigma = DUMMY_VAR__;
      current_statement__ = 3;
      logsigma = context__.vals_r("logsigma")[(1 - 1)];
      out__.write_free_ub(0, logsigma);
      Eigen::Matrix<local_scalar_t__,-1,1> zvalues =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(zvalues_1dim__,
          DUMMY_VAR__);
      {
        std::vector<local_scalar_t__> zvalues_flat__;
        current_statement__ = 4;
        zvalues_flat__ = context__.vals_r("zvalues");
        current_statement__ = 4;
        pos__ = 1;
        current_statement__ = 4;
        for (int sym1__ = 1; sym1__ <= zvalues_1dim__; ++sym1__) {
          current_statement__ = 4;
          stan::model::assign(zvalues, zvalues_flat__[(pos__ - 1)],
            "assigning variable zvalues", stan::model::index_uni(sym1__));
          current_statement__ = 4;
          pos__ = (pos__ + 1);
        }
      }
      out__.write(zvalues);
      local_scalar_t__ r1_global = DUMMY_VAR__;
      current_statement__ = 5;
      r1_global = context__.vals_r("r1_global")[(1 - 1)];
      out__.write_free_lb(0, r1_global);
      local_scalar_t__ r2_global = DUMMY_VAR__;
      current_statement__ = 6;
      r2_global = context__.vals_r("r2_global")[(1 - 1)];
      out__.write_free_lb(0, r2_global);
      Eigen::Matrix<local_scalar_t__,-1,1> r1_local =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(r1_local_1dim__,
          DUMMY_VAR__);
      {
        std::vector<local_scalar_t__> r1_local_flat__;
        current_statement__ = 7;
        r1_local_flat__ = context__.vals_r("r1_local");
        current_statement__ = 7;
        pos__ = 1;
        current_statement__ = 7;
        for (int sym1__ = 1; sym1__ <= r1_local_1dim__; ++sym1__) {
          current_statement__ = 7;
          stan::model::assign(r1_local, r1_local_flat__[(pos__ - 1)],
            "assigning variable r1_local", stan::model::index_uni(sym1__));
          current_statement__ = 7;
          pos__ = (pos__ + 1);
        }
      }
      out__.write_free_lb(0, r1_local);
      Eigen::Matrix<local_scalar_t__,-1,1> r2_local =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(r2_local_1dim__,
          DUMMY_VAR__);
      {
        std::vector<local_scalar_t__> r2_local_flat__;
        current_statement__ = 8;
        r2_local_flat__ = context__.vals_r("r2_local");
        current_statement__ = 8;
        pos__ = 1;
        current_statement__ = 8;
        for (int sym1__ = 1; sym1__ <= r2_local_1dim__; ++sym1__) {
          current_statement__ = 8;
          stan::model::assign(r2_local, r2_local_flat__[(pos__ - 1)],
            "assigning variable r2_local", stan::model::index_uni(sym1__));
          current_statement__ = 8;
          pos__ = (pos__ + 1);
        }
      }
      out__.write_free_lb(0, r2_local);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
  }
  inline void
  get_param_names(std::vector<std::string>& names__, const bool
                  emit_transformed_parameters__ = true, const bool
                  emit_generated_quantities__ = true) const {
    names__ = std::vector<std::string>{"beta0", "beta2", "logsigma",
                "zvalues", "r1_global", "r2_global", "r1_local", "r2_local"};
    if (emit_transformed_parameters__) {
      std::vector<std::string>
        temp{"tau", "lambda", "beta", "betaAll", "sigma"};
      names__.reserve(names__.size() + temp.size());
      names__.insert(names__.end(), temp.begin(), temp.end());
    }
    if (emit_generated_quantities__) {
      std::vector<std::string> temp{"log_lik"};
      names__.reserve(names__.size() + temp.size());
      names__.insert(names__.end(), temp.begin(), temp.end());
    }
  }
  inline void
  get_dims(std::vector<std::vector<size_t>>& dimss__, const bool
           emit_transformed_parameters__ = true, const bool
           emit_generated_quantities__ = true) const {
    dimss__ = std::vector<std::vector<size_t>>{std::vector<size_t>{static_cast<
                                                                    size_t>(
                                                                    K1)},
                std::vector<size_t>{static_cast<size_t>(K2)},
                std::vector<size_t>{},
                std::vector<size_t>{static_cast<size_t>(zvalues_1dim__)},
                std::vector<size_t>{}, std::vector<size_t>{},
                std::vector<size_t>{static_cast<size_t>(r1_local_1dim__)},
                std::vector<size_t>{static_cast<size_t>(r2_local_1dim__)}};
    if (emit_transformed_parameters__) {
      std::vector<std::vector<size_t>>
        temp{std::vector<size_t>{},
             std::vector<size_t>{static_cast<size_t>(lambda_1dim__)},
             std::vector<size_t>{static_cast<size_t>(beta_1dim__)},
             std::vector<size_t>{static_cast<size_t>(betaAll_1dim__)},
             std::vector<size_t>{static_cast<size_t>(N)}};
      dimss__.reserve(dimss__.size() + temp.size());
      dimss__.insert(dimss__.end(), temp.begin(), temp.end());
    }
    if (emit_generated_quantities__) {
      std::vector<std::vector<size_t>>
        temp{std::vector<size_t>{static_cast<size_t>(N)}};
      dimss__.reserve(dimss__.size() + temp.size());
      dimss__.insert(dimss__.end(), temp.begin(), temp.end());
    }
  }
  inline void
  constrained_param_names(std::vector<std::string>& param_names__, bool
                          emit_transformed_parameters__ = true, bool
                          emit_generated_quantities__ = true) const final {
    for (int sym1__ = 1; sym1__ <= K1; ++sym1__) {
      param_names__.emplace_back(std::string() + "beta0" + '.' +
        std::to_string(sym1__));
    }
    for (int sym1__ = 1; sym1__ <= K2; ++sym1__) {
      param_names__.emplace_back(std::string() + "beta2" + '.' +
        std::to_string(sym1__));
    }
    param_names__.emplace_back(std::string() + "logsigma");
    for (int sym1__ = 1; sym1__ <= zvalues_1dim__; ++sym1__) {
      param_names__.emplace_back(std::string() + "zvalues" + '.' +
        std::to_string(sym1__));
    }
    param_names__.emplace_back(std::string() + "r1_global");
    param_names__.emplace_back(std::string() + "r2_global");
    for (int sym1__ = 1; sym1__ <= r1_local_1dim__; ++sym1__) {
      param_names__.emplace_back(std::string() + "r1_local" + '.' +
        std::to_string(sym1__));
    }
    for (int sym1__ = 1; sym1__ <= r2_local_1dim__; ++sym1__) {
      param_names__.emplace_back(std::string() + "r2_local" + '.' +
        std::to_string(sym1__));
    }
    if (emit_transformed_parameters__) {
      param_names__.emplace_back(std::string() + "tau");
      for (int sym1__ = 1; sym1__ <= lambda_1dim__; ++sym1__) {
        param_names__.emplace_back(std::string() + "lambda" + '.' +
          std::to_string(sym1__));
      }
      for (int sym1__ = 1; sym1__ <= beta_1dim__; ++sym1__) {
        param_names__.emplace_back(std::string() + "beta" + '.' +
          std::to_string(sym1__));
      }
      for (int sym1__ = 1; sym1__ <= betaAll_1dim__; ++sym1__) {
        param_names__.emplace_back(std::string() + "betaAll" + '.' +
          std::to_string(sym1__));
      }
      for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
        param_names__.emplace_back(std::string() + "sigma" + '.' +
          std::to_string(sym1__));
      }
    }
    if (emit_generated_quantities__) {
      for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
        param_names__.emplace_back(std::string() + "log_lik" + '.' +
          std::to_string(sym1__));
      }
    }
  }
  inline void
  unconstrained_param_names(std::vector<std::string>& param_names__, bool
                            emit_transformed_parameters__ = true, bool
                            emit_generated_quantities__ = true) const final {
    for (int sym1__ = 1; sym1__ <= K1; ++sym1__) {
      param_names__.emplace_back(std::string() + "beta0" + '.' +
        std::to_string(sym1__));
    }
    for (int sym1__ = 1; sym1__ <= K2; ++sym1__) {
      param_names__.emplace_back(std::string() + "beta2" + '.' +
        std::to_string(sym1__));
    }
    param_names__.emplace_back(std::string() + "logsigma");
    for (int sym1__ = 1; sym1__ <= zvalues_1dim__; ++sym1__) {
      param_names__.emplace_back(std::string() + "zvalues" + '.' +
        std::to_string(sym1__));
    }
    param_names__.emplace_back(std::string() + "r1_global");
    param_names__.emplace_back(std::string() + "r2_global");
    for (int sym1__ = 1; sym1__ <= r1_local_1dim__; ++sym1__) {
      param_names__.emplace_back(std::string() + "r1_local" + '.' +
        std::to_string(sym1__));
    }
    for (int sym1__ = 1; sym1__ <= r2_local_1dim__; ++sym1__) {
      param_names__.emplace_back(std::string() + "r2_local" + '.' +
        std::to_string(sym1__));
    }
    if (emit_transformed_parameters__) {
      param_names__.emplace_back(std::string() + "tau");
      for (int sym1__ = 1; sym1__ <= lambda_1dim__; ++sym1__) {
        param_names__.emplace_back(std::string() + "lambda" + '.' +
          std::to_string(sym1__));
      }
      for (int sym1__ = 1; sym1__ <= beta_1dim__; ++sym1__) {
        param_names__.emplace_back(std::string() + "beta" + '.' +
          std::to_string(sym1__));
      }
      for (int sym1__ = 1; sym1__ <= betaAll_1dim__; ++sym1__) {
        param_names__.emplace_back(std::string() + "betaAll" + '.' +
          std::to_string(sym1__));
      }
      for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
        param_names__.emplace_back(std::string() + "sigma" + '.' +
          std::to_string(sym1__));
      }
    }
    if (emit_generated_quantities__) {
      for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
        param_names__.emplace_back(std::string() + "log_lik" + '.' +
          std::to_string(sym1__));
      }
    }
  }
  inline std::string get_constrained_sizedtypes() const {
    return std::string("[{\"name\":\"beta0\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(K1) + "},\"block\":\"parameters\"},{\"name\":\"beta2\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(K2) + "},\"block\":\"parameters\"},{\"name\":\"logsigma\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"zvalues\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(zvalues_1dim__) + "},\"block\":\"parameters\"},{\"name\":\"r1_global\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"r2_global\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"r1_local\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(r1_local_1dim__) + "},\"block\":\"parameters\"},{\"name\":\"r2_local\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(r2_local_1dim__) + "},\"block\":\"parameters\"},{\"name\":\"tau\",\"type\":{\"name\":\"real\"},\"block\":\"transformed_parameters\"},{\"name\":\"lambda\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(lambda_1dim__) + "},\"block\":\"transformed_parameters\"},{\"name\":\"beta\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(beta_1dim__) + "},\"block\":\"transformed_parameters\"},{\"name\":\"betaAll\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(betaAll_1dim__) + "},\"block\":\"transformed_parameters\"},{\"name\":\"sigma\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(N) + "},\"block\":\"transformed_parameters\"},{\"name\":\"log_lik\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(N) + "},\"block\":\"generated_quantities\"}]");
  }
  inline std::string get_unconstrained_sizedtypes() const {
    return std::string("[{\"name\":\"beta0\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(K1) + "},\"block\":\"parameters\"},{\"name\":\"beta2\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(K2) + "},\"block\":\"parameters\"},{\"name\":\"logsigma\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"zvalues\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(zvalues_1dim__) + "},\"block\":\"parameters\"},{\"name\":\"r1_global\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"r2_global\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"r1_local\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(r1_local_1dim__) + "},\"block\":\"parameters\"},{\"name\":\"r2_local\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(r2_local_1dim__) + "},\"block\":\"parameters\"},{\"name\":\"tau\",\"type\":{\"name\":\"real\"},\"block\":\"transformed_parameters\"},{\"name\":\"lambda\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(lambda_1dim__) + "},\"block\":\"transformed_parameters\"},{\"name\":\"beta\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(beta_1dim__) + "},\"block\":\"transformed_parameters\"},{\"name\":\"betaAll\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(betaAll_1dim__) + "},\"block\":\"transformed_parameters\"},{\"name\":\"sigma\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(N) + "},\"block\":\"transformed_parameters\"},{\"name\":\"log_lik\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(N) + "},\"block\":\"generated_quantities\"}]");
  }
  // Begin method overload boilerplate
  template <typename RNG> inline void
  write_array(RNG& base_rng, Eigen::Matrix<double,-1,1>& params_r,
              Eigen::Matrix<double,-1,1>& vars, const bool
              emit_transformed_parameters = true, const bool
              emit_generated_quantities = true, std::ostream*
              pstream = nullptr) const {
    const size_t num_params__ = (((((((K1 + K2) + 1) + zvalues_1dim__) + 1) +
      1) + r1_local_1dim__) + r2_local_1dim__);
    const size_t num_transformed = emit_transformed_parameters * (((((1 +
      lambda_1dim__) + beta_1dim__) + betaAll_1dim__) + N));
    const size_t num_gen_quantities = emit_generated_quantities * (N);
    const size_t num_to_write = num_params__ + num_transformed +
      num_gen_quantities;
    std::vector<int> params_i;
    vars = Eigen::Matrix<double,-1,1>::Constant(num_to_write,
             std::numeric_limits<double>::quiet_NaN());
    write_array_impl(base_rng, params_r, params_i, vars,
      emit_transformed_parameters, emit_generated_quantities, pstream);
  }
  template <typename RNG> inline void
  write_array(RNG& base_rng, std::vector<double>& params_r, std::vector<int>&
              params_i, std::vector<double>& vars, bool
              emit_transformed_parameters = true, bool
              emit_generated_quantities = true, std::ostream*
              pstream = nullptr) const {
    const size_t num_params__ = (((((((K1 + K2) + 1) + zvalues_1dim__) + 1) +
      1) + r1_local_1dim__) + r2_local_1dim__);
    const size_t num_transformed = emit_transformed_parameters * (((((1 +
      lambda_1dim__) + beta_1dim__) + betaAll_1dim__) + N));
    const size_t num_gen_quantities = emit_generated_quantities * (N);
    const size_t num_to_write = num_params__ + num_transformed +
      num_gen_quantities;
    vars = std::vector<double>(num_to_write,
             std::numeric_limits<double>::quiet_NaN());
    write_array_impl(base_rng, params_r, params_i, vars,
      emit_transformed_parameters, emit_generated_quantities, pstream);
  }
  template <bool propto__, bool jacobian__, typename T_> inline T_
  log_prob(Eigen::Matrix<T_,-1,1>& params_r, std::ostream* pstream = nullptr) const {
    Eigen::Matrix<int,-1,1> params_i;
    return log_prob_impl<propto__, jacobian__>(params_r, params_i, pstream);
  }
  template <bool propto__, bool jacobian__, typename T_> inline T_
  log_prob(std::vector<T_>& params_r, std::vector<int>& params_i,
           std::ostream* pstream = nullptr) const {
    return log_prob_impl<propto__, jacobian__>(params_r, params_i, pstream);
  }
  inline void
  transform_inits(const stan::io::var_context& context,
                  Eigen::Matrix<double,-1,1>& params_r, std::ostream*
                  pstream = nullptr) const final {
    std::vector<double> params_r_vec(params_r.size());
    std::vector<int> params_i;
    transform_inits(context, params_i, params_r_vec, pstream);
    params_r = Eigen::Map<Eigen::Matrix<double,-1,1>>(params_r_vec.data(),
                 params_r_vec.size());
  }
  inline void
  transform_inits(const stan::io::var_context& context, std::vector<int>&
                  params_i, std::vector<double>& vars, std::ostream*
                  pstream__ = nullptr) const {
    vars.resize(num_params_r__);
    transform_inits_impl(context, vars, pstream__);
  }
  inline void
  unconstrain_array(const std::vector<double>& params_constrained,
                    std::vector<double>& params_unconstrained, std::ostream*
                    pstream = nullptr) const {
    const std::vector<int> params_i;
    params_unconstrained = std::vector<double>(num_params_r__,
                             std::numeric_limits<double>::quiet_NaN());
    unconstrain_array_impl(params_constrained, params_i,
      params_unconstrained, pstream);
  }
  inline void
  unconstrain_array(const Eigen::Matrix<double,-1,1>& params_constrained,
                    Eigen::Matrix<double,-1,1>& params_unconstrained,
                    std::ostream* pstream = nullptr) const {
    const std::vector<int> params_i;
    params_unconstrained = Eigen::Matrix<double,-1,1>::Constant(num_params_r__,
                             std::numeric_limits<double>::quiet_NaN());
    unconstrain_array_impl(params_constrained, params_i,
      params_unconstrained, pstream);
  }
};
}
using stan_model = model_linRegHorseShoe_namespace::model_linRegHorseShoe;
#ifndef USING_R
// Boilerplate
stan::model::model_base&
new_model(stan::io::var_context& data_context, unsigned int seed,
          std::ostream* msg_stream) {
  stan_model* m = new stan_model(data_context, seed, msg_stream);
  return *m;
}
stan::math::profile_map& get_stan_profile_data() {
  return model_linRegHorseShoe_namespace::profiles__;
}
#endif
#endif
