// Generated by rstantools.  Do not edit by hand.

/*
    newPackage is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    newPackage is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with newPackage.  If not, see <http://www.gnu.org/licenses/>.
*/
#ifndef MODELS_HPP
#define MODELS_HPP
#define STAN__SERVICES__COMMAND_HPP
#ifndef USE_STANC3
#define USE_STANC3
#endif
#include <rstan/rstaninc.hpp>
// Code generated by stanc v2.32.2
#include <stan/model/model_header.hpp>
namespace model_linReg_namespace {
using stan::model::model_base_crtp;
using namespace stan::math;
stan::math::profile_map profiles__;
static constexpr std::array<const char*, 147> locations_array__ =
  {" (found before start of program)",
  " (in 'linReg', line 17, column 2 to column 19)",
  " (in 'linReg', line 18, column 2 to column 26)",
  " (in 'linReg', line 19, column 2 to column 26)",
  " (in 'linReg', line 20, column 2 to column 16)",
  " (in 'linReg', line 21, column 2 to column 24)",
  " (in 'linReg', line 22, column 2 to column 20)",
  " (in 'linReg', line 23, column 2 to column 28)",
  " (in 'linReg', line 26, column 2 to column 18)",
  " (in 'linReg', line 27, column 2 to column 20)",
  " (in 'linReg', line 28, column 2 to column 22)",
  " (in 'linReg', line 29, column 2 to column 20)",
  " (in 'linReg', line 30, column 2 to column 19)",
  " (in 'linReg', line 31, column 2 to column 16)",
  " (in 'linReg', line 100, column 2 to column 20)",
  " (in 'linReg', line 101, column 2 to column 20)",
  " (in 'linReg', line 102, column 2 to column 11)",
  " (in 'linReg', line 35, column 4 to column 20)",
  " (in 'linReg', line 34, column 9 to line 36, column 3)",
  " (in 'linReg', line 33, column 4 to column 19)",
  " (in 'linReg', line 32, column 16 to line 34, column 3)",
  " (in 'linReg', line 32, column 2 to line 36, column 3)",
  " (in 'linReg', line 37, column 2 to column 29)",
  " (in 'linReg', line 38, column 2 to column 74)",
  " (in 'linReg', line 39, column 2 to column 36)",
  " (in 'linReg', line 50, column 6 to column 39)",
  " (in 'linReg', line 51, column 6 to column 25)",
  " (in 'linReg', line 53, column 8 to column 60)",
  " (in 'linReg', line 54, column 8 to column 46)",
  " (in 'linReg', line 52, column 19 to line 55, column 7)",
  " (in 'linReg', line 52, column 6 to line 55, column 7)",
  " (in 'linReg', line 49, column 11 to line 56, column 5)",
  " (in 'linReg', line 43, column 6 to column 43)",
  " (in 'linReg', line 44, column 6 to column 25)",
  " (in 'linReg', line 46, column 8 to column 64)",
  " (in 'linReg', line 47, column 8 to column 46)",
  " (in 'linReg', line 45, column 19 to line 48, column 7)",
  " (in 'linReg', line 45, column 6 to line 48, column 7)",
  " (in 'linReg', line 42, column 12 to line 49, column 5)",
  " (in 'linReg', line 42, column 4 to line 56, column 5)",
  " (in 'linReg', line 41, column 9 to line 57, column 3)",
  " (in 'linReg', line 41, column 2 to line 57, column 3)",
  " (in 'linReg', line 40, column 13 to line 58, column 3)",
  " (in 'linReg', line 40, column 2 to line 58, column 3)",
  " (in 'linReg', line 103, column 17 to column 47)",
  " (in 'linReg', line 103, column 2 to column 47)",
  " (in 'linReg', line 104, column 2 to column 33)",
  " (in 'linReg', line 124, column 21 to column 81)",
  " (in 'linReg', line 124, column 6 to column 81)",
  " (in 'linReg', line 123, column 13 to line 125, column 7)",
  " (in 'linReg', line 121, column 8 to column 91)",
  " (in 'linReg', line 122, column 21 to column 100)",
  " (in 'linReg', line 122, column 6 to column 100)",
  " (in 'linReg', line 120, column 13 to line 123, column 7)",
  " (in 'linReg', line 120, column 6 to line 125, column 7)",
  " (in 'linReg', line 119, column 11 to line 126, column 5)",
  " (in 'linReg', line 118, column 23 to column 83)",
  " (in 'linReg', line 118, column 8 to column 83)",
  " (in 'linReg', line 117, column 14 to line 119, column 5)",
  " (in 'linReg', line 117, column 4 to line 126, column 5)",
  " (in 'linReg', line 116, column 9 to line 127, column 3)",
  " (in 'linReg', line 113, column 21 to column 152)",
  " (in 'linReg', line 113, column 6 to column 152)",
  " (in 'linReg', line 112, column 13 to line 114, column 6)",
  " (in 'linReg', line 110, column 8 to column 162)",
  " (in 'linReg', line 111, column 21 to column 171)",
  " (in 'linReg', line 111, column 6 to column 171)",
  " (in 'linReg', line 109, column 13 to line 112, column 7)",
  " (in 'linReg', line 109, column 6 to line 114, column 6)",
  " (in 'linReg', line 108, column 11 to line 115, column 5)",
  " (in 'linReg', line 107, column 21 to column 152)",
  " (in 'linReg', line 107, column 6 to column 152)",
  " (in 'linReg', line 106, column 14 to line 108, column 5)",
  " (in 'linReg', line 106, column 4 to line 115, column 5)",
  " (in 'linReg', line 105, column 10 to line 116, column 3)",
  " (in 'linReg', line 105, column 2 to line 127, column 3)",
  " (in 'linReg', line 61, column 2 to column 33)",
  " (in 'linReg', line 63, column 4 to column 32)",
  " (in 'linReg', line 62, column 12 to line 64, column 3)",
  " (in 'linReg', line 62, column 2 to line 64, column 3)",
  " (in 'linReg', line 65, column 2 to column 28)",
  " (in 'linReg', line 94, column 6 to column 37)",
  " (in 'linReg', line 93, column 11 to line 95, column 5)",
  " (in 'linReg', line 89, column 6 to column 70)",
  " (in 'linReg', line 91, column 8 to column 68)",
  " (in 'linReg', line 90, column 19 to line 92, column 7)",
  " (in 'linReg', line 90, column 6 to line 92, column 7)",
  " (in 'linReg', line 88, column 11 to line 93, column 5)",
  " (in 'linReg', line 88, column 4 to line 95, column 5)",
  " (in 'linReg', line 87, column 9 to line 96, column 3)",
  " (in 'linReg', line 86, column 4 to column 38)",
  " (in 'linReg', line 85, column 12 to line 87, column 3)",
  " (in 'linReg', line 85, column 2 to line 96, column 3)",
  " (in 'linReg', line 84, column 9 to line 97, column 3)",
  " (in 'linReg', line 67, column 2 to column 29)",
  " (in 'linReg', line 69, column 4 to column 38)",
  " (in 'linReg', line 70, column 4 to column 61)",
  " (in 'linReg', line 68, column 16 to line 71, column 3)",
  " (in 'linReg', line 68, column 2 to line 71, column 3)",
  " (in 'linReg', line 81, column 4 to column 39)",
  " (in 'linReg', line 80, column 11 to line 82, column 5)",
  " (in 'linReg', line 76, column 6 to column 74)",
  " (in 'linReg', line 78, column 6 to column 70)",
  " (in 'linReg', line 77, column 19 to line 79, column 7)",
  " (in 'linReg', line 77, column 6 to line 79, column 7)",
  " (in 'linReg', line 75, column 11 to line 80, column 5)",
  " (in 'linReg', line 75, column 4 to line 82, column 5)",
  " (in 'linReg', line 74, column 9 to line 83, column 3)",
  " (in 'linReg', line 73, column 4 to column 42)",
  " (in 'linReg', line 72, column 12 to line 74, column 3)",
  " (in 'linReg', line 72, column 2 to line 83, column 3)",
  " (in 'linReg', line 66, column 10 to line 84, column 3)",
  " (in 'linReg', line 66, column 2 to line 97, column 3)",
  " (in 'linReg', line 2, column 2 to column 8)",
  " (in 'linReg', line 3, column 2 to column 8)",
  " (in 'linReg', line 4, column 2 to column 9)",
  " (in 'linReg', line 5, column 2 to column 11)",
  " (in 'linReg', line 6, column 2 to column 17)",
  " (in 'linReg', line 7, column 2 to column 13)",
  " (in 'linReg', line 8, column 2 to column 10)",
  " (in 'linReg', line 9, column 2 to column 23)",
  " (in 'linReg', line 10, column 9 to column 10)",
  " (in 'linReg', line 10, column 2 to column 14)",
  " (in 'linReg', line 11, column 26 to column 27)",
  " (in 'linReg', line 11, column 2 to column 29)",
  " (in 'linReg', line 12, column 20 to column 21)",
  " (in 'linReg', line 12, column 2 to column 36)",
  " (in 'linReg', line 13, column 20 to column 21)",
  " (in 'linReg', line 13, column 22 to column 23)",
  " (in 'linReg', line 13, column 2 to column 44)",
  " (in 'linReg', line 14, column 9 to column 10)",
  " (in 'linReg', line 14, column 11 to column 12)",
  " (in 'linReg', line 14, column 2 to column 16)",
  " (in 'linReg', line 17, column 9 to column 11)",
  " (in 'linReg', line 18, column 10 to column 16)",
  " (in 'linReg', line 19, column 9 to column 15)",
  " (in 'linReg', line 21, column 9 to column 10)",
  " (in 'linReg', line 22, column 9 to column 10)",
  " (in 'linReg', line 22, column 11 to column 12)",
  " (in 'linReg', line 26, column 9 to column 10)",
  " (in 'linReg', line 27, column 9 to column 10)",
  " (in 'linReg', line 28, column 9 to column 15)",
  " (in 'linReg', line 29, column 9 to column 10)",
  " (in 'linReg', line 30, column 9 to column 10)",
  " (in 'linReg', line 31, column 9 to column 10)",
  " (in 'linReg', line 100, column 9 to column 10)",
  " (in 'linReg', line 101, column 9 to column 10)"};
#include <stan_meta_header.hpp>
class model_linReg final : public model_base_crtp<model_linReg> {
private:
  int N;
  int K;
  int K1;
  int xunc;
  int betaConstr;
  int logitR;
  int ar1;
  double varY;
  Eigen::Matrix<double,-1,1> y_data__;
  std::vector<int> yL;
  Eigen::Matrix<double,-1,1> yUncertainty_data__;
  Eigen::Matrix<double,-1,-1> xUncertaintyMatrix_data__;
  Eigen::Matrix<double,-1,-1> X_data__;
  int betaraw_1dim__;
  int betarawS_1dim__;
  int beta_1dim__;
  Eigen::Map<Eigen::Matrix<double,-1,1>> y{nullptr, 0};
  Eigen::Map<Eigen::Matrix<double,-1,1>> yUncertainty{nullptr, 0};
  Eigen::Map<Eigen::Matrix<double,-1,-1>> xUncertaintyMatrix{nullptr, 0, 0};
  Eigen::Map<Eigen::Matrix<double,-1,-1>> X{nullptr, 0, 0};
public:
  ~model_linReg() {}
  model_linReg(stan::io::var_context& context__, unsigned int
               random_seed__ = 0, std::ostream* pstream__ = nullptr)
      : model_base_crtp(0) {
    int current_statement__ = 0;
    using local_scalar_t__ = double;
    boost::ecuyer1988 base_rng__ =
      stan::services::util::create_rng(random_seed__, 0);
    // suppress unused var warning
    (void) base_rng__;
    static constexpr const char* function__ =
      "model_linReg_namespace::model_linReg";
    // suppress unused var warning
    (void) function__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    try {
      int pos__ = std::numeric_limits<int>::min();
      pos__ = 1;
      current_statement__ = 113;
      context__.validate_dims("data initialization", "N", "int",
        std::vector<size_t>{});
      N = std::numeric_limits<int>::min();
      current_statement__ = 113;
      N = context__.vals_i("N")[(1 - 1)];
      current_statement__ = 114;
      context__.validate_dims("data initialization", "K", "int",
        std::vector<size_t>{});
      K = std::numeric_limits<int>::min();
      current_statement__ = 114;
      K = context__.vals_i("K")[(1 - 1)];
      current_statement__ = 115;
      context__.validate_dims("data initialization", "K1", "int",
        std::vector<size_t>{});
      K1 = std::numeric_limits<int>::min();
      current_statement__ = 115;
      K1 = context__.vals_i("K1")[(1 - 1)];
      current_statement__ = 116;
      context__.validate_dims("data initialization", "xunc", "int",
        std::vector<size_t>{});
      xunc = std::numeric_limits<int>::min();
      current_statement__ = 116;
      xunc = context__.vals_i("xunc")[(1 - 1)];
      current_statement__ = 117;
      context__.validate_dims("data initialization", "betaConstr", "int",
        std::vector<size_t>{});
      betaConstr = std::numeric_limits<int>::min();
      current_statement__ = 117;
      betaConstr = context__.vals_i("betaConstr")[(1 - 1)];
      current_statement__ = 118;
      context__.validate_dims("data initialization", "logitR", "int",
        std::vector<size_t>{});
      logitR = std::numeric_limits<int>::min();
      current_statement__ = 118;
      logitR = context__.vals_i("logitR")[(1 - 1)];
      current_statement__ = 119;
      context__.validate_dims("data initialization", "ar1", "int",
        std::vector<size_t>{});
      ar1 = std::numeric_limits<int>::min();
      current_statement__ = 119;
      ar1 = context__.vals_i("ar1")[(1 - 1)];
      current_statement__ = 120;
      context__.validate_dims("data initialization", "varY", "double",
        std::vector<size_t>{});
      varY = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 120;
      varY = context__.vals_r("varY")[(1 - 1)];
      current_statement__ = 120;
      stan::math::check_greater_or_equal(function__, "varY", varY, 0);
      current_statement__ = 121;
      stan::math::validate_non_negative_index("y", "N", N);
      current_statement__ = 122;
      context__.validate_dims("data initialization", "y", "double",
        std::vector<size_t>{static_cast<size_t>(N)});
      y_data__ = Eigen::Matrix<double,-1,1>::Constant(N,
                   std::numeric_limits<double>::quiet_NaN());
      new (&y) Eigen::Map<Eigen::Matrix<double,-1,1>>(y_data__.data(), N);
      {
        std::vector<local_scalar_t__> y_flat__;
        current_statement__ = 122;
        y_flat__ = context__.vals_r("y");
        current_statement__ = 122;
        pos__ = 1;
        current_statement__ = 122;
        for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
          current_statement__ = 122;
          stan::model::assign(y, y_flat__[(pos__ - 1)],
            "assigning variable y", stan::model::index_uni(sym1__));
          current_statement__ = 122;
          pos__ = (pos__ + 1);
        }
      }
      current_statement__ = 123;
      stan::math::validate_non_negative_index("yL", "N", N);
      current_statement__ = 124;
      context__.validate_dims("data initialization", "yL", "int",
        std::vector<size_t>{static_cast<size_t>(N)});
      yL = std::vector<int>(N, std::numeric_limits<int>::min());
      current_statement__ = 124;
      yL = context__.vals_i("yL");
      current_statement__ = 124;
      stan::math::check_greater_or_equal(function__, "yL", yL, 0);
      current_statement__ = 124;
      stan::math::check_less_or_equal(function__, "yL", yL, 1);
      current_statement__ = 125;
      stan::math::validate_non_negative_index("yUncertainty", "N", N);
      current_statement__ = 126;
      context__.validate_dims("data initialization", "yUncertainty",
        "double", std::vector<size_t>{static_cast<size_t>(N)});
      yUncertainty_data__ = Eigen::Matrix<double,-1,1>::Constant(N,
                              std::numeric_limits<double>::quiet_NaN());
      new (&yUncertainty)
        Eigen::Map<Eigen::Matrix<double,-1,1>>(yUncertainty_data__.data(), N);
      {
        std::vector<local_scalar_t__> yUncertainty_flat__;
        current_statement__ = 126;
        yUncertainty_flat__ = context__.vals_r("yUncertainty");
        current_statement__ = 126;
        pos__ = 1;
        current_statement__ = 126;
        for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
          current_statement__ = 126;
          stan::model::assign(yUncertainty, yUncertainty_flat__[(pos__ - 1)],
            "assigning variable yUncertainty", stan::model::index_uni(sym1__));
          current_statement__ = 126;
          pos__ = (pos__ + 1);
        }
      }
      current_statement__ = 126;
      stan::math::check_greater_or_equal(function__, "yUncertainty",
        yUncertainty, 0);
      current_statement__ = 127;
      stan::math::validate_non_negative_index("xUncertaintyMatrix", "N", N);
      current_statement__ = 128;
      stan::math::validate_non_negative_index("xUncertaintyMatrix", "K", K);
      current_statement__ = 129;
      context__.validate_dims("data initialization", "xUncertaintyMatrix",
        "double",
        std::vector<size_t>{static_cast<size_t>(N), static_cast<size_t>(K)});
      xUncertaintyMatrix_data__ = Eigen::Matrix<double,-1,-1>::Constant(N, K,
                                    std::numeric_limits<double>::quiet_NaN());
      new (&xUncertaintyMatrix)
        Eigen::Map<Eigen::Matrix<double,-1,-1>>(xUncertaintyMatrix_data__.data(),
        N, K);
      {
        std::vector<local_scalar_t__> xUncertaintyMatrix_flat__;
        current_statement__ = 129;
        xUncertaintyMatrix_flat__ = context__.vals_r("xUncertaintyMatrix");
        current_statement__ = 129;
        pos__ = 1;
        current_statement__ = 129;
        for (int sym1__ = 1; sym1__ <= K; ++sym1__) {
          current_statement__ = 129;
          for (int sym2__ = 1; sym2__ <= N; ++sym2__) {
            current_statement__ = 129;
            stan::model::assign(xUncertaintyMatrix,
              xUncertaintyMatrix_flat__[(pos__ - 1)],
              "assigning variable xUncertaintyMatrix",
              stan::model::index_uni(sym2__), stan::model::index_uni(sym1__));
            current_statement__ = 129;
            pos__ = (pos__ + 1);
          }
        }
      }
      current_statement__ = 129;
      stan::math::check_greater_or_equal(function__, "xUncertaintyMatrix",
        xUncertaintyMatrix, 0);
      current_statement__ = 130;
      stan::math::validate_non_negative_index("X", "N", N);
      current_statement__ = 131;
      stan::math::validate_non_negative_index("X", "K", K);
      current_statement__ = 132;
      context__.validate_dims("data initialization", "X", "double",
        std::vector<size_t>{static_cast<size_t>(N), static_cast<size_t>(K)});
      X_data__ = Eigen::Matrix<double,-1,-1>::Constant(N, K,
                   std::numeric_limits<double>::quiet_NaN());
      new (&X) Eigen::Map<Eigen::Matrix<double,-1,-1>>(X_data__.data(), N, K);
      {
        std::vector<local_scalar_t__> X_flat__;
        current_statement__ = 132;
        X_flat__ = context__.vals_r("X");
        current_statement__ = 132;
        pos__ = 1;
        current_statement__ = 132;
        for (int sym1__ = 1; sym1__ <= K; ++sym1__) {
          current_statement__ = 132;
          for (int sym2__ = 1; sym2__ <= N; ++sym2__) {
            current_statement__ = 132;
            stan::model::assign(X, X_flat__[(pos__ - 1)],
              "assigning variable X", stan::model::index_uni(sym2__),
              stan::model::index_uni(sym1__));
            current_statement__ = 132;
            pos__ = (pos__ + 1);
          }
        }
      }
      current_statement__ = 133;
      stan::math::validate_non_negative_index("beta0", "K1", K1);
      current_statement__ = 134;
      betaraw_1dim__ = std::numeric_limits<int>::min();
      current_statement__ = 134;
      betaraw_1dim__ = (K - K1);
      current_statement__ = 134;
      stan::math::validate_positive_index("betaraw", "K - K1", betaraw_1dim__);
      current_statement__ = 135;
      betarawS_1dim__ = std::numeric_limits<int>::min();
      current_statement__ = 135;
      betarawS_1dim__ = (K - K1);
      current_statement__ = 135;
      stan::math::validate_non_negative_index("betarawS", "K - K1",
        betarawS_1dim__);
      current_statement__ = 136;
      stan::math::validate_non_negative_index("log_sigma_x", "K", K);
      current_statement__ = 137;
      stan::math::validate_non_negative_index("XTRUE", "N", N);
      current_statement__ = 138;
      stan::math::validate_non_negative_index("XTRUE", "K", K);
      current_statement__ = 139;
      stan::math::validate_non_negative_index("sigma", "N", N);
      current_statement__ = 140;
      stan::math::validate_non_negative_index("sigma_x", "K", K);
      current_statement__ = 141;
      beta_1dim__ = std::numeric_limits<int>::min();
      current_statement__ = 141;
      beta_1dim__ = (K - K1);
      current_statement__ = 141;
      stan::math::validate_non_negative_index("beta", "K - K1", beta_1dim__);
      current_statement__ = 142;
      stan::math::validate_non_negative_index("betaAll", "K", K);
      current_statement__ = 143;
      stan::math::validate_non_negative_index("epsAR1", "N", N);
      current_statement__ = 144;
      stan::math::validate_non_negative_index("eps", "N", N);
      current_statement__ = 145;
      stan::math::validate_non_negative_index("log_lik", "N", N);
      current_statement__ = 146;
      stan::math::validate_non_negative_index("sigmasq", "N", N);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
    num_params_r__ = K1 + (betaraw_1dim__ - 1) + betarawS_1dim__ + 1 + K + (N
      * K) + 1;
  }
  inline std::string model_name() const final {
    return "model_linReg";
  }
  inline std::vector<std::string> model_compile_info() const noexcept {
    return std::vector<std::string>{"stanc_version = stanc3 v2.32.2",
             "stancflags = --allow-undefined"};
  }
  template <bool propto__, bool jacobian__, typename VecR, typename VecI,
            stan::require_vector_like_t<VecR>* = nullptr,
            stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr>
  inline stan::scalar_type_t<VecR>
  log_prob_impl(VecR& params_r__, VecI& params_i__, std::ostream*
                pstream__ = nullptr) const {
    using T__ = stan::scalar_type_t<VecR>;
    using local_scalar_t__ = T__;
    T__ lp__(0.0);
    stan::math::accumulator<T__> lp_accum__;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    int current_statement__ = 0;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    static constexpr const char* function__ =
      "model_linReg_namespace::log_prob";
    // suppress unused var warning
    (void) function__;
    try {
      Eigen::Matrix<local_scalar_t__,-1,1> beta0 =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(K1, DUMMY_VAR__);
      current_statement__ = 1;
      beta0 = in__.template read<Eigen::Matrix<local_scalar_t__,-1,1>>(K1);
      Eigen::Matrix<local_scalar_t__,-1,1> betaraw =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(betaraw_1dim__,
          DUMMY_VAR__);
      current_statement__ = 2;
      betaraw = in__.template read_constrain_simplex<
                  Eigen::Matrix<local_scalar_t__,-1,1>, jacobian__>(lp__,
                  betaraw_1dim__);
      Eigen::Matrix<local_scalar_t__,-1,1> betarawS =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(betarawS_1dim__,
          DUMMY_VAR__);
      current_statement__ = 3;
      betarawS = in__.template read<
                   Eigen::Matrix<local_scalar_t__,-1,1>>(betarawS_1dim__);
      local_scalar_t__ logsigma = DUMMY_VAR__;
      current_statement__ = 4;
      logsigma = in__.template read<local_scalar_t__>();
      Eigen::Matrix<local_scalar_t__,-1,1> log_sigma_x =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(K, DUMMY_VAR__);
      current_statement__ = 5;
      log_sigma_x = in__.template read<
                      Eigen::Matrix<local_scalar_t__,-1,1>>(K);
      Eigen::Matrix<local_scalar_t__,-1,-1> XTRUE =
        Eigen::Matrix<local_scalar_t__,-1,-1>::Constant(N, K, DUMMY_VAR__);
      current_statement__ = 6;
      XTRUE = in__.template read<Eigen::Matrix<local_scalar_t__,-1,-1>>(N, K);
      local_scalar_t__ ar = DUMMY_VAR__;
      current_statement__ = 7;
      ar = in__.template read_constrain_lub<local_scalar_t__, jacobian__>(-1,
             1, lp__);
      Eigen::Matrix<local_scalar_t__,-1,1> sigma =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(N, DUMMY_VAR__);
      Eigen::Matrix<local_scalar_t__,-1,1> sigma_x =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(K, DUMMY_VAR__);
      Eigen::Matrix<local_scalar_t__,-1,1> beta =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(beta_1dim__,
          DUMMY_VAR__);
      Eigen::Matrix<local_scalar_t__,-1,1> betaAll =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(K, DUMMY_VAR__);
      Eigen::Matrix<local_scalar_t__,-1,1> epsAR1 =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(N, DUMMY_VAR__);
      Eigen::Matrix<local_scalar_t__,-1,1> eps =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(N, DUMMY_VAR__);
      current_statement__ = 21;
      if (betaConstr) {
        current_statement__ = 19;
        stan::model::assign(beta, betaraw, "assigning variable beta");
      } else {
        current_statement__ = 17;
        stan::model::assign(beta, betarawS, "assigning variable beta");
      }
      current_statement__ = 22;
      stan::model::assign(sigma_x, stan::math::exp(log_sigma_x),
        "assigning variable sigma_x");
      current_statement__ = 23;
      stan::model::assign(sigma,
        stan::math::sqrt(
          stan::math::add(
            stan::math::square((stan::math::exp(logsigma) *
              stan::math::sqrt(varY))), stan::math::square(yUncertainty))),
        "assigning variable sigma");
      current_statement__ = 24;
      stan::model::assign(betaAll, stan::math::append_row(beta0, beta),
        "assigning variable betaAll");
      current_statement__ = 43;
      if (stan::math::logical_negation(logitR)) {
        current_statement__ = 41;
        if (ar1) {
          current_statement__ = 39;
          if (xunc) {
            current_statement__ = 32;
            stan::model::assign(eps,
              (stan::model::rvalue(y, "y", stan::model::index_uni(1)) -
              stan::math::multiply(
                stan::model::rvalue(XTRUE, "XTRUE",
                  stan::model::index_uni(1), stan::model::index_omni()),
                betaAll)), "assigning variable eps",
              stan::model::index_uni(1));
            current_statement__ = 33;
            stan::model::assign(epsAR1,
              stan::model::rvalue(eps, "eps", stan::model::index_uni(1)),
              "assigning variable epsAR1", stan::model::index_uni(1));
            current_statement__ = 37;
            for (int i = 2; i <= N; ++i) {
              current_statement__ = 34;
              stan::model::assign(eps,
                ((stan::model::rvalue(y, "y", stan::model::index_uni(i)) -
                stan::math::multiply(
                  stan::model::rvalue(XTRUE, "XTRUE",
                    stan::model::index_uni(i), stan::model::index_omni()),
                  betaAll)) -
                (stan::model::rvalue(epsAR1, "epsAR1",
                   stan::model::index_uni((i - 1))) * ar)),
                "assigning variable eps", stan::model::index_uni(i));
              current_statement__ = 35;
              stan::model::assign(epsAR1,
                ((stan::model::rvalue(epsAR1, "epsAR1",
                    stan::model::index_uni((i - 1))) * ar) +
                stan::model::rvalue(eps, "eps", stan::model::index_uni(i))),
                "assigning variable epsAR1", stan::model::index_uni(i));
            }
          } else {
            current_statement__ = 25;
            stan::model::assign(eps,
              (stan::model::rvalue(y, "y", stan::model::index_uni(1)) -
              stan::math::multiply(
                stan::model::rvalue(X, "X", stan::model::index_uni(1),
                  stan::model::index_omni()), betaAll)),
              "assigning variable eps", stan::model::index_uni(1));
            current_statement__ = 26;
            stan::model::assign(epsAR1,
              stan::model::rvalue(eps, "eps", stan::model::index_uni(1)),
              "assigning variable epsAR1", stan::model::index_uni(1));
            current_statement__ = 30;
            for (int i = 2; i <= N; ++i) {
              current_statement__ = 27;
              stan::model::assign(eps,
                ((stan::model::rvalue(y, "y", stan::model::index_uni(i)) -
                stan::math::multiply(
                  stan::model::rvalue(X, "X", stan::model::index_uni(i),
                    stan::model::index_omni()), betaAll)) -
                (stan::model::rvalue(epsAR1, "epsAR1",
                   stan::model::index_uni((i - 1))) * ar)),
                "assigning variable eps", stan::model::index_uni(i));
              current_statement__ = 28;
              stan::model::assign(epsAR1,
                ((stan::model::rvalue(epsAR1, "epsAR1",
                    stan::model::index_uni((i - 1))) * ar) +
                stan::model::rvalue(eps, "eps", stan::model::index_uni(i))),
                "assigning variable epsAR1", stan::model::index_uni(i));
            }
          }
        }
      }
      {
        current_statement__ = 76;
        lp_accum__.add(stan::math::student_t_lpdf<propto__>(logsigma, 3, -2,
                         2));
        current_statement__ = 79;
        if (stan::math::logical_gt(K1, 0)) {
          current_statement__ = 77;
          lp_accum__.add(stan::math::student_t_lpdf<propto__>(beta0, 1, 0, 10));
        }
        current_statement__ = 80;
        lp_accum__.add(stan::math::student_t_lpdf<propto__>(beta, 3, 0, 5));
        current_statement__ = 112;
        if (xunc) {
          current_statement__ = 94;
          lp_accum__.add(stan::math::normal_lpdf<propto__>(log_sigma_x, 0, 1));
          current_statement__ = 98;
          for (int i = 1; i <= K; ++i) {
            current_statement__ = 95;
            lp_accum__.add(stan::math::normal_lpdf<propto__>(
                             stan::model::rvalue(XTRUE, "XTRUE",
                               stan::model::index_omni(),
                               stan::model::index_uni(i)), 0,
                             stan::model::rvalue(sigma_x, "sigma_x",
                               stan::model::index_uni(i))));
            current_statement__ = 96;
            lp_accum__.add(stan::math::normal_lpdf<propto__>(
                             stan::model::rvalue(X, "X",
                               stan::model::index_omni(),
                               stan::model::index_uni(i)),
                             stan::model::rvalue(XTRUE, "XTRUE",
                               stan::model::index_omni(),
                               stan::model::index_uni(i)),
                             stan::math::add(
                               stan::model::rvalue(xUncertaintyMatrix,
                                 "xUncertaintyMatrix",
                                 stan::model::index_omni(),
                                 stan::model::index_uni(i)), 1E-4)));
          }
          current_statement__ = 110;
          if (logitR) {
            current_statement__ = 108;
            lp_accum__.add(stan::math::bernoulli_logit_lpmf<propto__>(yL,
                             stan::math::multiply(XTRUE, betaAll)));
          } else {
            current_statement__ = 106;
            if (ar1) {
              current_statement__ = 101;
              lp_accum__.add(stan::math::normal_lpdf<propto__>(
                               stan::model::rvalue(y, "y",
                                 stan::model::index_uni(1)),
                               stan::math::multiply(
                                 stan::model::rvalue(XTRUE, "XTRUE",
                                   stan::model::index_uni(1),
                                   stan::model::index_omni()), betaAll),
                               (stan::model::rvalue(sigma, "sigma",
                                  stan::model::index_uni(1)) /
                               stan::math::sqrt((1 - stan::math::pow(ar, 2))))));
              current_statement__ = 104;
              for (int i = 2; i <= N; ++i) {
                current_statement__ = 102;
                lp_accum__.add(stan::math::normal_lpdf<propto__>(
                                 stan::model::rvalue(y, "y",
                                   stan::model::index_uni(i)),
                                 (stan::math::multiply(
                                    stan::model::rvalue(XTRUE, "XTRUE",
                                      stan::model::index_uni(i),
                                      stan::model::index_omni()), betaAll) +
                                 (stan::model::rvalue(epsAR1, "epsAR1",
                                    stan::model::index_uni((i - 1))) * ar)),
                                 stan::model::rvalue(sigma, "sigma",
                                   stan::model::index_uni(i))));
              }
            } else {
              current_statement__ = 99;
              lp_accum__.add(stan::math::normal_lpdf<propto__>(y,
                               stan::math::multiply(XTRUE, betaAll), sigma));
            }
          }
        } else {
          current_statement__ = 92;
          if (logitR) {
            current_statement__ = 90;
            lp_accum__.add(stan::math::bernoulli_logit_lpmf<propto__>(yL,
                             stan::math::multiply(X, betaAll)));
          } else {
            current_statement__ = 88;
            if (ar1) {
              current_statement__ = 83;
              lp_accum__.add(stan::math::normal_lpdf<propto__>(
                               stan::model::rvalue(y, "y",
                                 stan::model::index_uni(1)),
                               stan::math::multiply(
                                 stan::model::rvalue(X, "X",
                                   stan::model::index_uni(1),
                                   stan::model::index_omni()), betaAll),
                               (stan::model::rvalue(sigma, "sigma",
                                  stan::model::index_uni(1)) /
                               stan::math::sqrt((1 - stan::math::pow(ar, 2))))));
              current_statement__ = 86;
              for (int i = 2; i <= N; ++i) {
                current_statement__ = 84;
                lp_accum__.add(stan::math::normal_lpdf<propto__>(
                                 stan::model::rvalue(y, "y",
                                   stan::model::index_uni(i)),
                                 (stan::math::multiply(
                                    stan::model::rvalue(X, "X",
                                      stan::model::index_uni(i),
                                      stan::model::index_omni()), betaAll) +
                                 (stan::model::rvalue(epsAR1, "epsAR1",
                                    stan::model::index_uni((i - 1))) * ar)),
                                 stan::model::rvalue(sigma, "sigma",
                                   stan::model::index_uni(i))));
              }
            } else {
              current_statement__ = 81;
              lp_accum__.add(stan::math::normal_lpdf<propto__>(y,
                               stan::math::multiply(X, betaAll), sigma));
            }
          }
        }
      }
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
    lp_accum__.add(lp__);
    return lp_accum__.sum();
  }
  template <typename RNG, typename VecR, typename VecI, typename VecVar,
            stan::require_vector_like_vt<std::is_floating_point,
            VecR>* = nullptr, stan::require_vector_like_vt<std::is_integral,
            VecI>* = nullptr, stan::require_vector_vt<std::is_floating_point,
            VecVar>* = nullptr>
  inline void
  write_array_impl(RNG& base_rng__, VecR& params_r__, VecI& params_i__,
                   VecVar& vars__, const bool
                   emit_transformed_parameters__ = true, const bool
                   emit_generated_quantities__ = true, std::ostream*
                   pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    stan::io::serializer<local_scalar_t__> out__(vars__);
    static constexpr bool propto__ = true;
    // suppress unused var warning
    (void) propto__;
    double lp__ = 0.0;
    // suppress unused var warning
    (void) lp__;
    int current_statement__ = 0;
    stan::math::accumulator<double> lp_accum__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    constexpr bool jacobian__ = false;
    static constexpr const char* function__ =
      "model_linReg_namespace::write_array";
    // suppress unused var warning
    (void) function__;
    try {
      Eigen::Matrix<double,-1,1> beta0 =
        Eigen::Matrix<double,-1,1>::Constant(K1,
          std::numeric_limits<double>::quiet_NaN());
      current_statement__ = 1;
      beta0 = in__.template read<Eigen::Matrix<local_scalar_t__,-1,1>>(K1);
      Eigen::Matrix<double,-1,1> betaraw =
        Eigen::Matrix<double,-1,1>::Constant(betaraw_1dim__,
          std::numeric_limits<double>::quiet_NaN());
      current_statement__ = 2;
      betaraw = in__.template read_constrain_simplex<
                  Eigen::Matrix<local_scalar_t__,-1,1>, jacobian__>(lp__,
                  betaraw_1dim__);
      Eigen::Matrix<double,-1,1> betarawS =
        Eigen::Matrix<double,-1,1>::Constant(betarawS_1dim__,
          std::numeric_limits<double>::quiet_NaN());
      current_statement__ = 3;
      betarawS = in__.template read<
                   Eigen::Matrix<local_scalar_t__,-1,1>>(betarawS_1dim__);
      double logsigma = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 4;
      logsigma = in__.template read<local_scalar_t__>();
      Eigen::Matrix<double,-1,1> log_sigma_x =
        Eigen::Matrix<double,-1,1>::Constant(K,
          std::numeric_limits<double>::quiet_NaN());
      current_statement__ = 5;
      log_sigma_x = in__.template read<
                      Eigen::Matrix<local_scalar_t__,-1,1>>(K);
      Eigen::Matrix<double,-1,-1> XTRUE =
        Eigen::Matrix<double,-1,-1>::Constant(N, K,
          std::numeric_limits<double>::quiet_NaN());
      current_statement__ = 6;
      XTRUE = in__.template read<Eigen::Matrix<local_scalar_t__,-1,-1>>(N, K);
      double ar = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 7;
      ar = in__.template read_constrain_lub<local_scalar_t__, jacobian__>(-1,
             1, lp__);
      Eigen::Matrix<double,-1,1> sigma =
        Eigen::Matrix<double,-1,1>::Constant(N,
          std::numeric_limits<double>::quiet_NaN());
      Eigen::Matrix<double,-1,1> sigma_x =
        Eigen::Matrix<double,-1,1>::Constant(K,
          std::numeric_limits<double>::quiet_NaN());
      Eigen::Matrix<double,-1,1> beta =
        Eigen::Matrix<double,-1,1>::Constant(beta_1dim__,
          std::numeric_limits<double>::quiet_NaN());
      Eigen::Matrix<double,-1,1> betaAll =
        Eigen::Matrix<double,-1,1>::Constant(K,
          std::numeric_limits<double>::quiet_NaN());
      Eigen::Matrix<double,-1,1> epsAR1 =
        Eigen::Matrix<double,-1,1>::Constant(N,
          std::numeric_limits<double>::quiet_NaN());
      Eigen::Matrix<double,-1,1> eps =
        Eigen::Matrix<double,-1,1>::Constant(N,
          std::numeric_limits<double>::quiet_NaN());
      out__.write(beta0);
      out__.write(betaraw);
      out__.write(betarawS);
      out__.write(logsigma);
      out__.write(log_sigma_x);
      out__.write(XTRUE);
      out__.write(ar);
      if (stan::math::logical_negation(
            (stan::math::primitive_value(emit_transformed_parameters__) ||
            stan::math::primitive_value(emit_generated_quantities__)))) {
        return ;
      }
      current_statement__ = 21;
      if (betaConstr) {
        current_statement__ = 19;
        stan::model::assign(beta, betaraw, "assigning variable beta");
      } else {
        current_statement__ = 17;
        stan::model::assign(beta, betarawS, "assigning variable beta");
      }
      current_statement__ = 22;
      stan::model::assign(sigma_x, stan::math::exp(log_sigma_x),
        "assigning variable sigma_x");
      current_statement__ = 23;
      stan::model::assign(sigma,
        stan::math::sqrt(
          stan::math::add(
            stan::math::square((stan::math::exp(logsigma) *
              stan::math::sqrt(varY))), stan::math::square(yUncertainty))),
        "assigning variable sigma");
      current_statement__ = 24;
      stan::model::assign(betaAll, stan::math::append_row(beta0, beta),
        "assigning variable betaAll");
      current_statement__ = 43;
      if (stan::math::logical_negation(logitR)) {
        current_statement__ = 41;
        if (ar1) {
          current_statement__ = 39;
          if (xunc) {
            current_statement__ = 32;
            stan::model::assign(eps,
              (stan::model::rvalue(y, "y", stan::model::index_uni(1)) -
              stan::math::multiply(
                stan::model::rvalue(XTRUE, "XTRUE",
                  stan::model::index_uni(1), stan::model::index_omni()),
                betaAll)), "assigning variable eps",
              stan::model::index_uni(1));
            current_statement__ = 33;
            stan::model::assign(epsAR1,
              stan::model::rvalue(eps, "eps", stan::model::index_uni(1)),
              "assigning variable epsAR1", stan::model::index_uni(1));
            current_statement__ = 37;
            for (int i = 2; i <= N; ++i) {
              current_statement__ = 34;
              stan::model::assign(eps,
                ((stan::model::rvalue(y, "y", stan::model::index_uni(i)) -
                stan::math::multiply(
                  stan::model::rvalue(XTRUE, "XTRUE",
                    stan::model::index_uni(i), stan::model::index_omni()),
                  betaAll)) -
                (stan::model::rvalue(epsAR1, "epsAR1",
                   stan::model::index_uni((i - 1))) * ar)),
                "assigning variable eps", stan::model::index_uni(i));
              current_statement__ = 35;
              stan::model::assign(epsAR1,
                ((stan::model::rvalue(epsAR1, "epsAR1",
                    stan::model::index_uni((i - 1))) * ar) +
                stan::model::rvalue(eps, "eps", stan::model::index_uni(i))),
                "assigning variable epsAR1", stan::model::index_uni(i));
            }
          } else {
            current_statement__ = 25;
            stan::model::assign(eps,
              (stan::model::rvalue(y, "y", stan::model::index_uni(1)) -
              stan::math::multiply(
                stan::model::rvalue(X, "X", stan::model::index_uni(1),
                  stan::model::index_omni()), betaAll)),
              "assigning variable eps", stan::model::index_uni(1));
            current_statement__ = 26;
            stan::model::assign(epsAR1,
              stan::model::rvalue(eps, "eps", stan::model::index_uni(1)),
              "assigning variable epsAR1", stan::model::index_uni(1));
            current_statement__ = 30;
            for (int i = 2; i <= N; ++i) {
              current_statement__ = 27;
              stan::model::assign(eps,
                ((stan::model::rvalue(y, "y", stan::model::index_uni(i)) -
                stan::math::multiply(
                  stan::model::rvalue(X, "X", stan::model::index_uni(i),
                    stan::model::index_omni()), betaAll)) -
                (stan::model::rvalue(epsAR1, "epsAR1",
                   stan::model::index_uni((i - 1))) * ar)),
                "assigning variable eps", stan::model::index_uni(i));
              current_statement__ = 28;
              stan::model::assign(epsAR1,
                ((stan::model::rvalue(epsAR1, "epsAR1",
                    stan::model::index_uni((i - 1))) * ar) +
                stan::model::rvalue(eps, "eps", stan::model::index_uni(i))),
                "assigning variable epsAR1", stan::model::index_uni(i));
            }
          }
        }
      }
      if (emit_transformed_parameters__) {
        out__.write(sigma);
        out__.write(sigma_x);
        out__.write(beta);
        out__.write(betaAll);
        out__.write(epsAR1);
        out__.write(eps);
      }
      if (stan::math::logical_negation(emit_generated_quantities__)) {
        return ;
      }
      Eigen::Matrix<double,-1,1> log_lik =
        Eigen::Matrix<double,-1,1>::Constant(N,
          std::numeric_limits<double>::quiet_NaN());
      Eigen::Matrix<double,-1,1> sigmasq =
        Eigen::Matrix<double,-1,1>::Constant(N,
          std::numeric_limits<double>::quiet_NaN());
      double rsq = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 45;
      for (int n = 1; n <= N; ++n) {
        current_statement__ = 44;
        stan::model::assign(sigmasq,
          stan::math::square(
            stan::model::rvalue(sigma, "sigma", stan::model::index_uni(n))),
          "assigning variable sigmasq", stan::model::index_uni(n));
      }
      current_statement__ = 46;
      rsq = (1 - (stan::math::mean(sigmasq) / varY));
      current_statement__ = 75;
      if (xunc) {
        current_statement__ = 73;
        if (logitR) {
          current_statement__ = 71;
          for (int n = 1; n <= N; ++n) {
            current_statement__ = 70;
            stan::model::assign(log_lik,
              (stan::math::bernoulli_logit_lpmf<false>(
                 stan::model::rvalue(yL, "yL", stan::model::index_uni(n)),
                 stan::math::multiply(
                   stan::model::rvalue(XTRUE, "XTRUE",
                     stan::model::index_uni(n), stan::model::index_omni()),
                   betaAll)) +
              stan::math::normal_lpdf<false>(
                stan::model::rvalue(X, "X", stan::model::index_uni(n),
                  stan::model::index_omni()),
                stan::model::rvalue(XTRUE, "XTRUE",
                  stan::model::index_uni(n), stan::model::index_omni()),
                stan::math::add(
                  stan::model::rvalue(xUncertaintyMatrix,
                    "xUncertaintyMatrix", stan::model::index_uni(n),
                    stan::model::index_omni()), 1E-4))),
              "assigning variable log_lik", stan::model::index_uni(n));
          }
        } else {
          current_statement__ = 68;
          if (ar1) {
            current_statement__ = 64;
            stan::model::assign(log_lik,
              (stan::math::normal_lpdf<false>(
                 stan::model::rvalue(y, "y", stan::model::index_uni(1)),
                 stan::math::multiply(
                   stan::model::rvalue(XTRUE, "XTRUE",
                     stan::model::index_uni(1), stan::model::index_omni()),
                   betaAll),
                 (stan::model::rvalue(sigma, "sigma",
                    stan::model::index_uni(1)) /
                 stan::math::sqrt((1 - stan::math::pow(ar, 2))))) +
              stan::math::normal_lpdf<false>(
                stan::model::rvalue(X, "X", stan::model::index_uni(1),
                  stan::model::index_omni()),
                stan::model::rvalue(XTRUE, "XTRUE",
                  stan::model::index_uni(1), stan::model::index_omni()),
                stan::math::add(
                  stan::model::rvalue(xUncertaintyMatrix,
                    "xUncertaintyMatrix", stan::model::index_uni(1),
                    stan::model::index_omni()), 1E-4))),
              "assigning variable log_lik", stan::model::index_uni(1));
            current_statement__ = 66;
            for (int n = 2; n <= N; ++n) {
              current_statement__ = 65;
              stan::model::assign(log_lik,
                (stan::math::normal_lpdf<false>(
                   stan::model::rvalue(y, "y", stan::model::index_uni(n)),
                   (stan::math::multiply(
                      stan::model::rvalue(XTRUE, "XTRUE",
                        stan::model::index_uni(n), stan::model::index_omni()),
                      betaAll) +
                   (stan::model::rvalue(epsAR1, "epsAR1",
                      stan::model::index_uni((n - 1))) * ar)),
                   stan::model::rvalue(sigma, "sigma",
                     stan::model::index_uni(n))) +
                stan::math::normal_lpdf<false>(
                  stan::model::rvalue(X, "X", stan::model::index_uni(n),
                    stan::model::index_omni()),
                  stan::model::rvalue(XTRUE, "XTRUE",
                    stan::model::index_uni(n), stan::model::index_omni()),
                  stan::math::add(
                    stan::model::rvalue(xUncertaintyMatrix,
                      "xUncertaintyMatrix", stan::model::index_uni(n),
                      stan::model::index_omni()), 1E-4))),
                "assigning variable log_lik", stan::model::index_uni(n));
            }
          } else {
            current_statement__ = 62;
            for (int n = 1; n <= N; ++n) {
              current_statement__ = 61;
              stan::model::assign(log_lik,
                (stan::math::normal_lpdf<false>(
                   stan::model::rvalue(y, "y", stan::model::index_uni(n)),
                   stan::math::multiply(
                     stan::model::rvalue(XTRUE, "XTRUE",
                       stan::model::index_uni(n), stan::model::index_omni()),
                     betaAll),
                   stan::model::rvalue(sigma, "sigma",
                     stan::model::index_uni(n))) +
                stan::math::normal_lpdf<false>(
                  stan::model::rvalue(X, "X", stan::model::index_uni(n),
                    stan::model::index_omni()),
                  stan::model::rvalue(XTRUE, "XTRUE",
                    stan::model::index_uni(n), stan::model::index_omni()),
                  stan::math::add(
                    stan::model::rvalue(xUncertaintyMatrix,
                      "xUncertaintyMatrix", stan::model::index_uni(n),
                      stan::model::index_omni()), 1E-4))),
                "assigning variable log_lik", stan::model::index_uni(n));
            }
          }
        }
      } else {
        current_statement__ = 59;
        if (logitR) {
          current_statement__ = 57;
          for (int n = 1; n <= N; ++n) {
            current_statement__ = 56;
            stan::model::assign(log_lik,
              stan::math::bernoulli_logit_lpmf<false>(
                stan::model::rvalue(yL, "yL", stan::model::index_uni(n)),
                stan::math::multiply(
                  stan::model::rvalue(X, "X", stan::model::index_uni(n),
                    stan::model::index_omni()), betaAll)),
              "assigning variable log_lik", stan::model::index_uni(n));
          }
        } else {
          current_statement__ = 54;
          if (ar1) {
            current_statement__ = 50;
            stan::model::assign(log_lik,
              stan::math::normal_lpdf<false>(
                stan::model::rvalue(y, "y", stan::model::index_uni(1)),
                stan::math::multiply(
                  stan::model::rvalue(X, "X", stan::model::index_uni(1),
                    stan::model::index_omni()), betaAll),
                (stan::model::rvalue(sigma, "sigma",
                   stan::model::index_uni(1)) /
                stan::math::sqrt((1 - stan::math::pow(ar, 2))))),
              "assigning variable log_lik", stan::model::index_uni(1));
            current_statement__ = 52;
            for (int n = 2; n <= N; ++n) {
              current_statement__ = 51;
              stan::model::assign(log_lik,
                stan::math::normal_lpdf<false>(
                  stan::model::rvalue(y, "y", stan::model::index_uni(n)),
                  (stan::math::multiply(
                     stan::model::rvalue(X, "X", stan::model::index_uni(n),
                       stan::model::index_omni()), betaAll) +
                  (stan::model::rvalue(epsAR1, "epsAR1",
                     stan::model::index_uni((n - 1))) * ar)),
                  stan::model::rvalue(sigma, "sigma",
                    stan::model::index_uni(n))),
                "assigning variable log_lik", stan::model::index_uni(n));
            }
          } else {
            current_statement__ = 48;
            for (int n = 1; n <= N; ++n) {
              current_statement__ = 47;
              stan::model::assign(log_lik,
                stan::math::normal_lpdf<false>(
                  stan::model::rvalue(y, "y", stan::model::index_uni(n)),
                  stan::math::multiply(
                    stan::model::rvalue(X, "X", stan::model::index_uni(n),
                      stan::model::index_omni()), betaAll),
                  stan::model::rvalue(sigma, "sigma",
                    stan::model::index_uni(n))),
                "assigning variable log_lik", stan::model::index_uni(n));
            }
          }
        }
      }
      out__.write(log_lik);
      out__.write(sigmasq);
      out__.write(rsq);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
  }
  template <typename VecVar, typename VecI,
            stan::require_vector_t<VecVar>* = nullptr,
            stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr>
  inline void
  unconstrain_array_impl(const VecVar& params_r__, const VecI& params_i__,
                         VecVar& vars__, std::ostream* pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    stan::io::serializer<local_scalar_t__> out__(vars__);
    int current_statement__ = 0;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    try {
      int pos__ = std::numeric_limits<int>::min();
      pos__ = 1;
      Eigen::Matrix<local_scalar_t__,-1,1> beta0 =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(K1, DUMMY_VAR__);
      current_statement__ = 1;
      stan::model::assign(beta0,
        in__.read<Eigen::Matrix<local_scalar_t__,-1,1>>(K1),
        "assigning variable beta0");
      out__.write(beta0);
      Eigen::Matrix<local_scalar_t__,-1,1> betaraw =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(betaraw_1dim__,
          DUMMY_VAR__);
      current_statement__ = 2;
      stan::model::assign(betaraw,
        in__.read<Eigen::Matrix<local_scalar_t__,-1,1>>(betaraw_1dim__),
        "assigning variable betaraw");
      out__.write_free_simplex(betaraw);
      Eigen::Matrix<local_scalar_t__,-1,1> betarawS =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(betarawS_1dim__,
          DUMMY_VAR__);
      current_statement__ = 3;
      stan::model::assign(betarawS,
        in__.read<Eigen::Matrix<local_scalar_t__,-1,1>>(betarawS_1dim__),
        "assigning variable betarawS");
      out__.write(betarawS);
      local_scalar_t__ logsigma = DUMMY_VAR__;
      current_statement__ = 4;
      logsigma = in__.read<local_scalar_t__>();
      out__.write(logsigma);
      Eigen::Matrix<local_scalar_t__,-1,1> log_sigma_x =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(K, DUMMY_VAR__);
      current_statement__ = 5;
      stan::model::assign(log_sigma_x,
        in__.read<Eigen::Matrix<local_scalar_t__,-1,1>>(K),
        "assigning variable log_sigma_x");
      out__.write(log_sigma_x);
      Eigen::Matrix<local_scalar_t__,-1,-1> XTRUE =
        Eigen::Matrix<local_scalar_t__,-1,-1>::Constant(N, K, DUMMY_VAR__);
      current_statement__ = 6;
      stan::model::assign(XTRUE,
        in__.read<Eigen::Matrix<local_scalar_t__,-1,-1>>(N, K),
        "assigning variable XTRUE");
      out__.write(XTRUE);
      local_scalar_t__ ar = DUMMY_VAR__;
      current_statement__ = 7;
      ar = in__.read<local_scalar_t__>();
      out__.write_free_lub(-1, 1, ar);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
  }
  template <typename VecVar, stan::require_vector_t<VecVar>* = nullptr>
  inline void
  transform_inits_impl(const stan::io::var_context& context__, VecVar&
                       vars__, std::ostream* pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    stan::io::serializer<local_scalar_t__> out__(vars__);
    int current_statement__ = 0;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    try {
      current_statement__ = 1;
      context__.validate_dims("parameter initialization", "beta0", "double",
        std::vector<size_t>{static_cast<size_t>(K1)});
      current_statement__ = 2;
      context__.validate_dims("parameter initialization", "betaraw",
        "double", std::vector<size_t>{static_cast<size_t>(betaraw_1dim__)});
      current_statement__ = 3;
      context__.validate_dims("parameter initialization", "betarawS",
        "double", std::vector<size_t>{static_cast<size_t>(betarawS_1dim__)});
      current_statement__ = 4;
      context__.validate_dims("parameter initialization", "logsigma",
        "double", std::vector<size_t>{});
      current_statement__ = 5;
      context__.validate_dims("parameter initialization", "log_sigma_x",
        "double", std::vector<size_t>{static_cast<size_t>(K)});
      current_statement__ = 6;
      context__.validate_dims("parameter initialization", "XTRUE", "double",
        std::vector<size_t>{static_cast<size_t>(N), static_cast<size_t>(K)});
      current_statement__ = 7;
      context__.validate_dims("parameter initialization", "ar", "double",
        std::vector<size_t>{});
      int pos__ = std::numeric_limits<int>::min();
      pos__ = 1;
      Eigen::Matrix<local_scalar_t__,-1,1> beta0 =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(K1, DUMMY_VAR__);
      {
        std::vector<local_scalar_t__> beta0_flat__;
        current_statement__ = 1;
        beta0_flat__ = context__.vals_r("beta0");
        current_statement__ = 1;
        pos__ = 1;
        current_statement__ = 1;
        for (int sym1__ = 1; sym1__ <= K1; ++sym1__) {
          current_statement__ = 1;
          stan::model::assign(beta0, beta0_flat__[(pos__ - 1)],
            "assigning variable beta0", stan::model::index_uni(sym1__));
          current_statement__ = 1;
          pos__ = (pos__ + 1);
        }
      }
      out__.write(beta0);
      Eigen::Matrix<local_scalar_t__,-1,1> betaraw =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(betaraw_1dim__,
          DUMMY_VAR__);
      {
        std::vector<local_scalar_t__> betaraw_flat__;
        current_statement__ = 2;
        betaraw_flat__ = context__.vals_r("betaraw");
        current_statement__ = 2;
        pos__ = 1;
        current_statement__ = 2;
        for (int sym1__ = 1; sym1__ <= betaraw_1dim__; ++sym1__) {
          current_statement__ = 2;
          stan::model::assign(betaraw, betaraw_flat__[(pos__ - 1)],
            "assigning variable betaraw", stan::model::index_uni(sym1__));
          current_statement__ = 2;
          pos__ = (pos__ + 1);
        }
      }
      out__.write_free_simplex(betaraw);
      Eigen::Matrix<local_scalar_t__,-1,1> betarawS =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(betarawS_1dim__,
          DUMMY_VAR__);
      {
        std::vector<local_scalar_t__> betarawS_flat__;
        current_statement__ = 3;
        betarawS_flat__ = context__.vals_r("betarawS");
        current_statement__ = 3;
        pos__ = 1;
        current_statement__ = 3;
        for (int sym1__ = 1; sym1__ <= betarawS_1dim__; ++sym1__) {
          current_statement__ = 3;
          stan::model::assign(betarawS, betarawS_flat__[(pos__ - 1)],
            "assigning variable betarawS", stan::model::index_uni(sym1__));
          current_statement__ = 3;
          pos__ = (pos__ + 1);
        }
      }
      out__.write(betarawS);
      local_scalar_t__ logsigma = DUMMY_VAR__;
      current_statement__ = 4;
      logsigma = context__.vals_r("logsigma")[(1 - 1)];
      out__.write(logsigma);
      Eigen::Matrix<local_scalar_t__,-1,1> log_sigma_x =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(K, DUMMY_VAR__);
      {
        std::vector<local_scalar_t__> log_sigma_x_flat__;
        current_statement__ = 5;
        log_sigma_x_flat__ = context__.vals_r("log_sigma_x");
        current_statement__ = 5;
        pos__ = 1;
        current_statement__ = 5;
        for (int sym1__ = 1; sym1__ <= K; ++sym1__) {
          current_statement__ = 5;
          stan::model::assign(log_sigma_x, log_sigma_x_flat__[(pos__ - 1)],
            "assigning variable log_sigma_x", stan::model::index_uni(sym1__));
          current_statement__ = 5;
          pos__ = (pos__ + 1);
        }
      }
      out__.write(log_sigma_x);
      Eigen::Matrix<local_scalar_t__,-1,-1> XTRUE =
        Eigen::Matrix<local_scalar_t__,-1,-1>::Constant(N, K, DUMMY_VAR__);
      {
        std::vector<local_scalar_t__> XTRUE_flat__;
        current_statement__ = 6;
        XTRUE_flat__ = context__.vals_r("XTRUE");
        current_statement__ = 6;
        pos__ = 1;
        current_statement__ = 6;
        for (int sym1__ = 1; sym1__ <= K; ++sym1__) {
          current_statement__ = 6;
          for (int sym2__ = 1; sym2__ <= N; ++sym2__) {
            current_statement__ = 6;
            stan::model::assign(XTRUE, XTRUE_flat__[(pos__ - 1)],
              "assigning variable XTRUE", stan::model::index_uni(sym2__),
              stan::model::index_uni(sym1__));
            current_statement__ = 6;
            pos__ = (pos__ + 1);
          }
        }
      }
      out__.write(XTRUE);
      local_scalar_t__ ar = DUMMY_VAR__;
      current_statement__ = 7;
      ar = context__.vals_r("ar")[(1 - 1)];
      out__.write_free_lub(-1, 1, ar);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
  }
  inline void
  get_param_names(std::vector<std::string>& names__, const bool
                  emit_transformed_parameters__ = true, const bool
                  emit_generated_quantities__ = true) const {
    names__ = std::vector<std::string>{"beta0", "betaraw", "betarawS",
                "logsigma", "log_sigma_x", "XTRUE", "ar"};
    if (emit_transformed_parameters__) {
      std::vector<std::string>
        temp{"sigma", "sigma_x", "beta", "betaAll", "epsAR1", "eps"};
      names__.reserve(names__.size() + temp.size());
      names__.insert(names__.end(), temp.begin(), temp.end());
    }
    if (emit_generated_quantities__) {
      std::vector<std::string> temp{"log_lik", "sigmasq", "rsq"};
      names__.reserve(names__.size() + temp.size());
      names__.insert(names__.end(), temp.begin(), temp.end());
    }
  }
  inline void
  get_dims(std::vector<std::vector<size_t>>& dimss__, const bool
           emit_transformed_parameters__ = true, const bool
           emit_generated_quantities__ = true) const {
    dimss__ = std::vector<std::vector<size_t>>{std::vector<size_t>{static_cast<
                                                                    size_t>(
                                                                    K1)},
                std::vector<size_t>{static_cast<size_t>(betaraw_1dim__)},
                std::vector<size_t>{static_cast<size_t>(betarawS_1dim__)},
                std::vector<size_t>{},
                std::vector<size_t>{static_cast<size_t>(K)},
                std::vector<size_t>{static_cast<size_t>(N),
                  static_cast<size_t>(K)}, std::vector<size_t>{}};
    if (emit_transformed_parameters__) {
      std::vector<std::vector<size_t>>
        temp{std::vector<size_t>{static_cast<size_t>(N)},
             std::vector<size_t>{static_cast<size_t>(K)},
             std::vector<size_t>{static_cast<size_t>(beta_1dim__)},
             std::vector<size_t>{static_cast<size_t>(K)},
             std::vector<size_t>{static_cast<size_t>(N)},
             std::vector<size_t>{static_cast<size_t>(N)}};
      dimss__.reserve(dimss__.size() + temp.size());
      dimss__.insert(dimss__.end(), temp.begin(), temp.end());
    }
    if (emit_generated_quantities__) {
      std::vector<std::vector<size_t>>
        temp{std::vector<size_t>{static_cast<size_t>(N)},
             std::vector<size_t>{static_cast<size_t>(N)},
             std::vector<size_t>{}};
      dimss__.reserve(dimss__.size() + temp.size());
      dimss__.insert(dimss__.end(), temp.begin(), temp.end());
    }
  }
  inline void
  constrained_param_names(std::vector<std::string>& param_names__, bool
                          emit_transformed_parameters__ = true, bool
                          emit_generated_quantities__ = true) const final {
    for (int sym1__ = 1; sym1__ <= K1; ++sym1__) {
      param_names__.emplace_back(std::string() + "beta0" + '.' +
        std::to_string(sym1__));
    }
    for (int sym1__ = 1; sym1__ <= betaraw_1dim__; ++sym1__) {
      param_names__.emplace_back(std::string() + "betaraw" + '.' +
        std::to_string(sym1__));
    }
    for (int sym1__ = 1; sym1__ <= betarawS_1dim__; ++sym1__) {
      param_names__.emplace_back(std::string() + "betarawS" + '.' +
        std::to_string(sym1__));
    }
    param_names__.emplace_back(std::string() + "logsigma");
    for (int sym1__ = 1; sym1__ <= K; ++sym1__) {
      param_names__.emplace_back(std::string() + "log_sigma_x" + '.' +
        std::to_string(sym1__));
    }
    for (int sym1__ = 1; sym1__ <= K; ++sym1__) {
      for (int sym2__ = 1; sym2__ <= N; ++sym2__) {
        param_names__.emplace_back(std::string() + "XTRUE" + '.' +
          std::to_string(sym2__) + '.' + std::to_string(sym1__));
      }
    }
    param_names__.emplace_back(std::string() + "ar");
    if (emit_transformed_parameters__) {
      for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
        param_names__.emplace_back(std::string() + "sigma" + '.' +
          std::to_string(sym1__));
      }
      for (int sym1__ = 1; sym1__ <= K; ++sym1__) {
        param_names__.emplace_back(std::string() + "sigma_x" + '.' +
          std::to_string(sym1__));
      }
      for (int sym1__ = 1; sym1__ <= beta_1dim__; ++sym1__) {
        param_names__.emplace_back(std::string() + "beta" + '.' +
          std::to_string(sym1__));
      }
      for (int sym1__ = 1; sym1__ <= K; ++sym1__) {
        param_names__.emplace_back(std::string() + "betaAll" + '.' +
          std::to_string(sym1__));
      }
      for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
        param_names__.emplace_back(std::string() + "epsAR1" + '.' +
          std::to_string(sym1__));
      }
      for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
        param_names__.emplace_back(std::string() + "eps" + '.' +
          std::to_string(sym1__));
      }
    }
    if (emit_generated_quantities__) {
      for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
        param_names__.emplace_back(std::string() + "log_lik" + '.' +
          std::to_string(sym1__));
      }
      for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
        param_names__.emplace_back(std::string() + "sigmasq" + '.' +
          std::to_string(sym1__));
      }
      param_names__.emplace_back(std::string() + "rsq");
    }
  }
  inline void
  unconstrained_param_names(std::vector<std::string>& param_names__, bool
                            emit_transformed_parameters__ = true, bool
                            emit_generated_quantities__ = true) const final {
    for (int sym1__ = 1; sym1__ <= K1; ++sym1__) {
      param_names__.emplace_back(std::string() + "beta0" + '.' +
        std::to_string(sym1__));
    }
    for (int sym1__ = 1; sym1__ <= (betaraw_1dim__ - 1); ++sym1__) {
      param_names__.emplace_back(std::string() + "betaraw" + '.' +
        std::to_string(sym1__));
    }
    for (int sym1__ = 1; sym1__ <= betarawS_1dim__; ++sym1__) {
      param_names__.emplace_back(std::string() + "betarawS" + '.' +
        std::to_string(sym1__));
    }
    param_names__.emplace_back(std::string() + "logsigma");
    for (int sym1__ = 1; sym1__ <= K; ++sym1__) {
      param_names__.emplace_back(std::string() + "log_sigma_x" + '.' +
        std::to_string(sym1__));
    }
    for (int sym1__ = 1; sym1__ <= K; ++sym1__) {
      for (int sym2__ = 1; sym2__ <= N; ++sym2__) {
        param_names__.emplace_back(std::string() + "XTRUE" + '.' +
          std::to_string(sym2__) + '.' + std::to_string(sym1__));
      }
    }
    param_names__.emplace_back(std::string() + "ar");
    if (emit_transformed_parameters__) {
      for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
        param_names__.emplace_back(std::string() + "sigma" + '.' +
          std::to_string(sym1__));
      }
      for (int sym1__ = 1; sym1__ <= K; ++sym1__) {
        param_names__.emplace_back(std::string() + "sigma_x" + '.' +
          std::to_string(sym1__));
      }
      for (int sym1__ = 1; sym1__ <= beta_1dim__; ++sym1__) {
        param_names__.emplace_back(std::string() + "beta" + '.' +
          std::to_string(sym1__));
      }
      for (int sym1__ = 1; sym1__ <= K; ++sym1__) {
        param_names__.emplace_back(std::string() + "betaAll" + '.' +
          std::to_string(sym1__));
      }
      for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
        param_names__.emplace_back(std::string() + "epsAR1" + '.' +
          std::to_string(sym1__));
      }
      for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
        param_names__.emplace_back(std::string() + "eps" + '.' +
          std::to_string(sym1__));
      }
    }
    if (emit_generated_quantities__) {
      for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
        param_names__.emplace_back(std::string() + "log_lik" + '.' +
          std::to_string(sym1__));
      }
      for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
        param_names__.emplace_back(std::string() + "sigmasq" + '.' +
          std::to_string(sym1__));
      }
      param_names__.emplace_back(std::string() + "rsq");
    }
  }
  inline std::string get_constrained_sizedtypes() const {
    return std::string("[{\"name\":\"beta0\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(K1) + "},\"block\":\"parameters\"},{\"name\":\"betaraw\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(betaraw_1dim__) + "},\"block\":\"parameters\"},{\"name\":\"betarawS\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(betarawS_1dim__) + "},\"block\":\"parameters\"},{\"name\":\"logsigma\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"log_sigma_x\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(K) + "},\"block\":\"parameters\"},{\"name\":\"XTRUE\",\"type\":{\"name\":\"matrix\",\"rows\":" + std::to_string(N) + ",\"cols\":" + std::to_string(K) + "},\"block\":\"parameters\"},{\"name\":\"ar\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"sigma\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(N) + "},\"block\":\"transformed_parameters\"},{\"name\":\"sigma_x\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(K) + "},\"block\":\"transformed_parameters\"},{\"name\":\"beta\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(beta_1dim__) + "},\"block\":\"transformed_parameters\"},{\"name\":\"betaAll\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(K) + "},\"block\":\"transformed_parameters\"},{\"name\":\"epsAR1\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(N) + "},\"block\":\"transformed_parameters\"},{\"name\":\"eps\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(N) + "},\"block\":\"transformed_parameters\"},{\"name\":\"log_lik\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(N) + "},\"block\":\"generated_quantities\"},{\"name\":\"sigmasq\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(N) + "},\"block\":\"generated_quantities\"},{\"name\":\"rsq\",\"type\":{\"name\":\"real\"},\"block\":\"generated_quantities\"}]");
  }
  inline std::string get_unconstrained_sizedtypes() const {
    return std::string("[{\"name\":\"beta0\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(K1) + "},\"block\":\"parameters\"},{\"name\":\"betaraw\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string((betaraw_1dim__ -1)) + "},\"block\":\"parameters\"},{\"name\":\"betarawS\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(betarawS_1dim__) + "},\"block\":\"parameters\"},{\"name\":\"logsigma\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"log_sigma_x\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(K) + "},\"block\":\"parameters\"},{\"name\":\"XTRUE\",\"type\":{\"name\":\"matrix\",\"rows\":" + std::to_string(N) + ",\"cols\":" + std::to_string(K) + "},\"block\":\"parameters\"},{\"name\":\"ar\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"sigma\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(N) + "},\"block\":\"transformed_parameters\"},{\"name\":\"sigma_x\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(K) + "},\"block\":\"transformed_parameters\"},{\"name\":\"beta\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(beta_1dim__) + "},\"block\":\"transformed_parameters\"},{\"name\":\"betaAll\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(K) + "},\"block\":\"transformed_parameters\"},{\"name\":\"epsAR1\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(N) + "},\"block\":\"transformed_parameters\"},{\"name\":\"eps\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(N) + "},\"block\":\"transformed_parameters\"},{\"name\":\"log_lik\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(N) + "},\"block\":\"generated_quantities\"},{\"name\":\"sigmasq\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(N) + "},\"block\":\"generated_quantities\"},{\"name\":\"rsq\",\"type\":{\"name\":\"real\"},\"block\":\"generated_quantities\"}]");
  }
  // Begin method overload boilerplate
  template <typename RNG> inline void
  write_array(RNG& base_rng, Eigen::Matrix<double,-1,1>& params_r,
              Eigen::Matrix<double,-1,1>& vars, const bool
              emit_transformed_parameters = true, const bool
              emit_generated_quantities = true, std::ostream*
              pstream = nullptr) const {
    const size_t num_params__ = ((((((K1 + betaraw_1dim__) + betarawS_1dim__)
      + 1) + K) + (N * K)) + 1);
    const size_t num_transformed = emit_transformed_parameters * ((((((N + K)
      + beta_1dim__) + K) + N) + N));
    const size_t num_gen_quantities = emit_generated_quantities * (((N + N) +
      1));
    const size_t num_to_write = num_params__ + num_transformed +
      num_gen_quantities;
    std::vector<int> params_i;
    vars = Eigen::Matrix<double,-1,1>::Constant(num_to_write,
             std::numeric_limits<double>::quiet_NaN());
    write_array_impl(base_rng, params_r, params_i, vars,
      emit_transformed_parameters, emit_generated_quantities, pstream);
  }
  template <typename RNG> inline void
  write_array(RNG& base_rng, std::vector<double>& params_r, std::vector<int>&
              params_i, std::vector<double>& vars, bool
              emit_transformed_parameters = true, bool
              emit_generated_quantities = true, std::ostream*
              pstream = nullptr) const {
    const size_t num_params__ = ((((((K1 + betaraw_1dim__) + betarawS_1dim__)
      + 1) + K) + (N * K)) + 1);
    const size_t num_transformed = emit_transformed_parameters * ((((((N + K)
      + beta_1dim__) + K) + N) + N));
    const size_t num_gen_quantities = emit_generated_quantities * (((N + N) +
      1));
    const size_t num_to_write = num_params__ + num_transformed +
      num_gen_quantities;
    vars = std::vector<double>(num_to_write,
             std::numeric_limits<double>::quiet_NaN());
    write_array_impl(base_rng, params_r, params_i, vars,
      emit_transformed_parameters, emit_generated_quantities, pstream);
  }
  template <bool propto__, bool jacobian__, typename T_> inline T_
  log_prob(Eigen::Matrix<T_,-1,1>& params_r, std::ostream* pstream = nullptr) const {
    Eigen::Matrix<int,-1,1> params_i;
    return log_prob_impl<propto__, jacobian__>(params_r, params_i, pstream);
  }
  template <bool propto__, bool jacobian__, typename T_> inline T_
  log_prob(std::vector<T_>& params_r, std::vector<int>& params_i,
           std::ostream* pstream = nullptr) const {
    return log_prob_impl<propto__, jacobian__>(params_r, params_i, pstream);
  }
  inline void
  transform_inits(const stan::io::var_context& context,
                  Eigen::Matrix<double,-1,1>& params_r, std::ostream*
                  pstream = nullptr) const final {
    std::vector<double> params_r_vec(params_r.size());
    std::vector<int> params_i;
    transform_inits(context, params_i, params_r_vec, pstream);
    params_r = Eigen::Map<Eigen::Matrix<double,-1,1>>(params_r_vec.data(),
                 params_r_vec.size());
  }
  inline void
  transform_inits(const stan::io::var_context& context, std::vector<int>&
                  params_i, std::vector<double>& vars, std::ostream*
                  pstream__ = nullptr) const {
    vars.resize(num_params_r__);
    transform_inits_impl(context, vars, pstream__);
  }
  inline void
  unconstrain_array(const std::vector<double>& params_constrained,
                    std::vector<double>& params_unconstrained, std::ostream*
                    pstream = nullptr) const {
    const std::vector<int> params_i;
    params_unconstrained = std::vector<double>(num_params_r__,
                             std::numeric_limits<double>::quiet_NaN());
    unconstrain_array_impl(params_constrained, params_i,
      params_unconstrained, pstream);
  }
  inline void
  unconstrain_array(const Eigen::Matrix<double,-1,1>& params_constrained,
                    Eigen::Matrix<double,-1,1>& params_unconstrained,
                    std::ostream* pstream = nullptr) const {
    const std::vector<int> params_i;
    params_unconstrained = Eigen::Matrix<double,-1,1>::Constant(num_params_r__,
                             std::numeric_limits<double>::quiet_NaN());
    unconstrain_array_impl(params_constrained, params_i,
      params_unconstrained, pstream);
  }
};
}
using stan_model = model_linReg_namespace::model_linReg;
#ifndef USING_R
// Boilerplate
stan::model::model_base&
new_model(stan::io::var_context& data_context, unsigned int seed,
          std::ostream* msg_stream) {
  stan_model* m = new stan_model(data_context, seed, msg_stream);
  return *m;
}
stan::math::profile_map& get_stan_profile_data() {
  return model_linReg_namespace::profiles__;
}
#endif
#endif
